<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Curso de R</title>

<script src="site_libs/header-attrs-2.6/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>





<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Semana i</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fas fa-home"></span>
     
    Home
  </a>
</li>
<li>
  <a href="about.html">
    <span class="fas fa-folder"></span>
     
    Curso
  </a>
</li>
<li>
  <a href="material.html">
    <span class="fas fa-archive"></span>
     
    Proyectos
  </a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="mailto:luisbv@tec.mx">
    <span class="fas fa-envelope-o"></span>
     
    Contáctame
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Curso de R</h1>

</div>


<div id="section" class="section level1 tabset tabset-fade tabset-pills">
<h1 class="tabset tabset-fade tabset-pills"></h1>
<div id="introducción" class="section level2">
<h2>Introducción</h2>
<div id="instalación-de-r" class="section level3">
<h3>Instalación de R</h3>
<p>Para utilizar R es necesario instalarlo en tu máquina. Para ello sigue las instrucciones en <a href="https://cran.r-project.org/" class="uri">https://cran.r-project.org/</a>.</p>
<p>Para facilitar la programación en R, es necesario descargar otro software que asista como interfaz de usuario, creando un ambiente integrado de desarrollo (o IDE por sus siglas en inglés).</p>
<p>Uno de los IDE más utilizados en R es el RStudio, y este se puede descargar libremente de <a href="https://www.rstudio.com" class="uri">https://www.rstudio.com</a>.</p>
</div>
<div id="descripción-de-r" class="section level3">
<h3>Descripción de R</h3>
<p>R es un software de fuente libre para su uso en estadística. Se modeló a raíz de S y S-Plus. El lenguaje S fue desarrollado a finales de los 80’s en los laboratorios de <strong>AT&amp;T</strong>. El proyecto R fue iniciado por Robert Gentleman y Ross Ihaka en el Departamento de Estadística de la Universidad de Auckland en 1995. <a href="https://cran.r-project.org">sitio web oficial</a></p>
</div>
<div id="uso-de-r-en-el-curso" class="section level3">
<h3>Uso de R en el curso</h3>
<p>Se pretende utilizar R en lugar de otras opciones comerciales como lo son <code>Minitab</code>, <code>Spss</code>, <code>Excel</code>, etc. Se espera que esto permita a los alumnos entender de mejor manera los problemas estadísticos y se beneficio de la utilización de un programa más sofisticado a pesar de la curva de aprendizaje menos pronunciada.</p>
</div>
<div id="beneficios-esperados-para-los-alumnos" class="section level3">
<h3>Beneficios esperados para los alumnos</h3>
<p>Se espera que los alumnos aprecien los siguientes beneficios:</p>
<ul>
<li>R es gratis.</li>
<li>R es de código abierto, corre en sistemas <strong>Unix</strong> (y similares), <strong>Windows</strong> y <strong>Macintosh</strong>.</li>
<li>R tiene un sistema de ayuda muy amplio.</li>
<li>R permite diseñar y manipular gráficas.</li>
<li>Aprendiendo R, los alumnos pueden luego migrar a otras plataformar comerciales como S, o S-plus.</li>
<li>R tiene una sintaxis fácil de aprender y está lleno de funciones estadísticas listas para usarse.</li>
<li>R es un lenguaje computacional de alto nivel.</li>
</ul>
</div>
<div id="r-en-comparación-con-otras-soluciones-de-software" class="section level3">
<h3>R en comparación con otras soluciones de software}</h3>
<p>¿Qué le falta a R en comparación a otros?</p>
<ul>
<li>La interfaz gráfica es limitada. Esto quiere decir es que un poco más difícil de crear y manipular gráficas que con otros paquetes, no que no las pueda hacer.</li>
<li>No hay soporte comercial. Sin embargo la abundante ayuda que existe en la red compensa en buena medida este hecho.</li>
<li>El lenguaje de comandos es un lenguaje de programación, por lo que los estudiantes deberán aprender a apreciar los beneficios y maleficios de la sintaxis.</li>
</ul>
</div>
</div>
<div id="primeros-pasos" class="section level2">
<h2>Primeros Pasos</h2>
<div id="iniciando-r" class="section level3">
<h3>Iniciando R</h3>
<p>Iniciar R es algo directo, pero el método depende de tu plataforma. Lo podrás correr desde el menú del sistema al hacer doble clic en el íncono de R, o agregando el comando <code>R</code> en la línea de comandos.</p>
</div>
<div id="pantalla-de-bienvenida" class="section level3">
<h3>Pantalla de bienvenida</h3>
<blockquote>
<p>R version 3.2.1 (2015-06-18) – “World-Famous Astronaut” Copyright (C) 2015 The R Foundation for Statistical Computing Platform: i386-w64-mingw32/i386 (32-bit)</p>
<p>R is free software and comes with ABSOLUTELY NO WARRANTY. You are welcome to redistribute it under certain conditions. Type ‘license()’ or ‘licence()’ for distribution details.</p>
<p>R is a collaborative project with many contributors. Type ‘contributors()’ for more information and ‘citation()’ on how to cite R or R packages in publications.</p>
<p>Type ‘demo()’ for some demos, ‘help()’ for on-line help, or ‘help.start()’ for an HTML browser interface to help. Type ‘q()’ to quit R.</p>
<p>[Workspace loaded from ~/.RData]</p>
<blockquote>

</blockquote>
</blockquote>
</div>
<div id="preguntas-y-respuestas" class="section level3">
<h3>Preguntas y respuestas</h3>
<p>R se utiliza de manera interactiva, el usuario hace una pregunta y R te da una repuesta.</p>
<ul>
<li>Ingresas una línea con un comando y luego presionas <code>return</code>.</li>
<li>Cuando R está listo para recibir entradas, mostrará <code>&gt;</code>.</li>
<li>Es posible utilizar R escribiendo línea por línea, o en forma de lotes, donde escribes muchas líneas y le pides a R que las ejecute todas con una sola orden.</li>
</ul>
</div>
<div id="ejemplo-1" class="section level3">
<h3>Ejemplo 1</h3>
<pre class="r"><code>plot(rnorm(500))</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>Este comando dibuja 500 números aleatorios de una distribución normal estándar en una gráfica que se genera.</p>
</div>
<div id="ejemplo-2" class="section level3">
<h3>Ejemplo 2</h3>
<p>R lo puedes usar como una calculadora. Prueba con los siguientes comandos:</p>
<pre class="r"><code>2 + 2</code></pre>
<pre><code>## [1] 4</code></pre>
<pre class="r"><code>exp(-2)</code></pre>
<pre><code>## [1] 0.1353353</code></pre>
<ul>
<li>El <code>[1]</code> es la forma que tiene R de imprimir números y vectores.</li>
<li>No es muy útil en estos momentos, pero lo será cuando los resultados sean vectores de mayor tamaño.</li>
</ul>
</div>
<div id="ejemplo-2-1" class="section level3">
<h3>Ejemplo 2</h3>
<p>Considera el comando:</p>
<pre class="r"><code>rnorm(15)</code></pre>
<pre><code>##  [1]  1.131322762 -1.110886620 -0.505608019 -0.869268531 -0.000982745
##  [6] -0.263335715  0.207682464 -1.436852421  0.658340678 -1.962553435
## [11]  0.144678106 -0.143019585  0.192640865 -0.095227610 -0.259289874</code></pre>
<ul>
<li>El <code>[1]</code> indica la posición del primer resultado en el vector de 15 elementos.</li>
<li>El <code>[8]</code> indica que el valor <code>-1.4368524</code> está en la posición 8.</li>
<li>El <code>[15]</code> indica que el valor <code>-0.2592899</code> está en la posición 15.</li>
<li>Las posiciones de los demás valores se pueden obtener contando a partir del elemento de la izquierda. Por ejemplo, <code>-1.1108866</code> tiene la posición 2, pues <code>1.1313228</code> que está a su izquierda tiene la posición 1. Así, <code>-0.505608</code> tiene la posición 3, <code>-0.8692685</code> la 4, etc.</li>
</ul>
</div>
<div id="asignaciones" class="section level3">
<h3>Asignaciones</h3>
<p>R, como cualquier otro lenguaje computacional, tiene <em>variables simbólicas</em>. Estos son nombres que representan valores. Por ejemplo, para asignar el valor 2 a la variable <code>x</code></p>
<pre class="r"><code>x &lt;- 2</code></pre>
<p>Ahora prueba utilizar la variable</p>
<pre class="r"><code>x</code></pre>
<pre><code>## [1] 2</code></pre>
<pre class="r"><code>x + x</code></pre>
<pre><code>## [1] 4</code></pre>
</div>
<div id="nombres-de-tus-variables" class="section level3">
<h3>Nombres de tus variables</h3>
<p>Los nombres de las variables pueden elegirse libremente, pero debes seguir estas reglas:</p>
<ul>
<li>Los nombres se pueden construir de letras, dígitos y puntos.</li>
<li>Un nombre no puede iniciar con un dígito y un punto seguido de un dígito.</li>
<li>Nombres que inician con punto son especiales y deben evitarse.</li>
<li>Un ejemplo de nombre de variable: height.1yr puede representar la altura de un niño de un año de edad.</li>
<li>Los nombres son sensibles a las mayúsculas. WT no es lo mismo que wt.</li>
<li>Algunos nombres ya los usa el sistema y pueden causas confusiones si los usas para otros propósitos: <code>c</code>, <code>q</code>, <code>t</code>, <code>C</code>, <code>D</code>, <code>F</code>, <code>I</code>, y <code>T</code>, así como <code>diff</code>, <code>df</code>, y <code>pt</code>. <span style="color:red">¡No úses estos nombres!</span></li>
</ul>
</div>
<div id="aritmética-vectorizada" class="section level3">
<h3>Aritmética vectorizada</h3>
<p>En estadística raras veces trabajas con un sólo dato, ocupas conjuntos de datos. Estos conjunto se pueden agrupar a través de vectores.</p>
<pre class="r"><code>weight &lt;- c(60, 72, 57, 90, 95, 72)
weight</code></pre>
<pre><code>## [1] 60 72 57 90 95 72</code></pre>
<p>La función <code>c(...)</code> se usa para definir vectores.</p>
<p>Ahora puedes hacer cálculos aritméticos utilizando vectores.</p>
<pre class="r"><code>height &lt;- c(1.75, 1.80, 1.65, 1.90, 1.74, 1.91)
bmi &lt;- weight / height^2
bmi</code></pre>
<pre><code>## [1] 19.59184 22.22222 20.93664 24.93075 31.37799 19.73630</code></pre>
<p>Nota que las operaciones se hacen elemento por elemento de cada vector.</p>
<blockquote>
<h4 id="reciclaje"><em>Reciclaje</em></h4>
<p><span style="color:red">Si un vector es menor que otro, el vector de menor longitud se recicla. Esto es mayormente usado en vectores de tamaño 1 (escalares), pero también cuando se desean lograr un patrón. Si el vector de mayor tamaño no es múltiplo del de menor tamaño, R ejecuta el cálculo pero arroja una advertencia.</span></p>
</blockquote>
</div>
<div id="ejemplo" class="section level3">
<h3>Ejemplo</h3>
<p>Calculemos la media y la desviación estándar de la variable <code>weight</code>.</p>
<pre class="r"><code>sum(weight)</code></pre>
<pre><code>## [1] 446</code></pre>
<pre class="r"><code>sum(weight) / length(weight)</code></pre>
<pre><code>## [1] 74.33333</code></pre>
<p>Para salvar la media y usarla en el cálculo de la desviación estándar:</p>
<pre class="r"><code>xbar &lt;- sum(weight) / length(weight)
weight - xbar</code></pre>
<pre><code>## [1] -14.333333  -2.333333 -17.333333  15.666667  20.666667  -2.333333</code></pre>
<pre class="r"><code>(weight - xbar)^2</code></pre>
<pre><code>## [1] 205.444444   5.444444 300.444444 245.444444 427.111111   5.444444</code></pre>
<pre class="r"><code>sum((weight - xbar)^2)</code></pre>
<pre><code>## [1] 1189.333</code></pre>
<pre class="r"><code>sqrt(sum((weight - xbar)^2))/(length(weight) - 1)</code></pre>
<pre><code>## [1] 6.897342</code></pre>
</div>
<div id="ejemplo-3" class="section level3">
<h3>Ejemplo</h3>
<p>Otra forma de lograr el mismo resultado es mediante las funciones <code>mean(...)</code> y <code>sd(...)</code></p>
<pre class="r"><code>mean(weight)</code></pre>
<pre><code>## [1] 74.33333</code></pre>
<pre class="r"><code>sd(weight)</code></pre>
<pre><code>## [1] 15.42293</code></pre>
</div>
<div id="ejemplo-de-prueba-de-hipótesis" class="section level3">
<h3>Ejemplo de Prueba de Hipótesis</h3>
<div id="prueba-t" class="section level4">
<h4>Prueba <strong>t</strong></h4>
<p>Usando lo datos calculados del BMI, prueba si la media de los 6 BMI’s calculados anteriormente es 22.5 o no lo es. Usa la prueba <strong>t</strong> para averiguarlo.</p>
<pre class="r"><code>t.test(bmi,mu=22.5)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  bmi
## t = 0.34488, df = 5, p-value = 0.7442
## alternative hypothesis: true mean is not equal to 22.5
## 95 percent confidence interval:
##  18.41734 27.84791
## sample estimates:
## mean of x 
##  23.13262</code></pre>
</div>
<div id="gráficas" class="section level4">
<h4>Gráficas</h4>
<p>R puede ayudarnos a visualizar los datos mediante el uso de gráficas.</p>
<pre class="r"><code>plot(height,weight)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>Debido a que un BMI normal debe ser alrededor de 22.5, se espera que <span class="math inline">\(weight \approx 22.5 \times height^2\)</span>. Esta línea la podemos incluir en la figura.</p>
<pre class="r"><code>hh &lt;- c(1.65, 1.70, 1.75, 1.80, 1.85, 1.90)
lines(hh, 22.5 * hh^2)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>La función <code>lines(...)</code> agrega valores (<code>x</code>,<code>y</code>) conectados por líneas.</p>
<blockquote>
<h4 id="nota">Nota</h4>
<p>En el ejemplo se utilizó como entrada de la función la variable <code>hh</code> para aproximar la línea curva por medio de líneas equidistantes ordenadas. Prueba utilizar otros valores de entrada para averiguar que sucede si estos no están ordenados o no so equidistantes.</p>
</blockquote>
</div>
</div>
<div id="elmentos-esenciales-del-lenguaje-r" class="section level3">
<h3>Elmentos Esenciales del Lenguaje R</h3>
<div id="expresiones-y-objetos" class="section level4">
<h4>Expresiones y Objetos</h4>
<p>La forma de interactuar con R es a través de expresiones.</p>
<ul>
<li>El usuario ingresa una expresión, R la evalúa e imprime el resultado.</li>
<li>Algunas expresiones se evalúan no por su resultado, sino por su efecto secundario, como una imagen o escribir en un archivo.</li>
<li>Todas las expresiones regresan un resultado, que puede ser <code>NULL</code>, y a veces puede ser invisible.</li>
<li>Las expresiones involucran variables de referencia, operadores como <code>+</code>, llamadas de funciones, y otras que todavía no se mencionan.</li>
<li>Las expresiones trabajan en <em>objetos</em>. Este es un término abstracto para referirse a cualquier cosa que se puede asignar a una variable. Un vector es un ejemplo de un objeto.</li>
</ul>
</div>
<div id="funciones-y-argumentos" class="section level4">
<h4>Funciones y Argumentos</h4>
<p>Muchas cosas en R se hacen llamando funciones. Estas son análogas a lo que en matemáticas se le conoce como función de una o más variables. Por ejemplo:</p>
<pre class="r"><code>log(x)
plot(height,weight)</code></pre>
<p>En el último caso, la función se llama <code>plot</code> y los argumentos son <code>height</code> y <code>weight</code>.</p>
<p>Una función puede tener muchos argumentos. Para ver los argumentos se una función en específico se puede utilizar la función <code>arg</code>.</p>
<pre class="r"><code>args(plot.default)</code></pre>
<pre><code>## function (x, y = NULL, type = &quot;p&quot;, xlim = NULL, ylim = NULL, 
##     log = &quot;&quot;, main = NULL, sub = NULL, xlab = NULL, ylab = NULL, 
##     ann = par(&quot;ann&quot;), axes = TRUE, frame.plot = axes, panel.first = NULL, 
##     panel.last = NULL, asp = NA, xgap.axis = NA, ygap.axis = NA, 
##     ...) 
## NULL</code></pre>
<p>Los argumentos que no están seguido por un igual son argumentos obligatorios. Mientras que los que están seguidor por un igual son opcionales. Los opcionales, de no establecerse, quedan definidos por un valor por defecto.</p>
<p>Prueba incluir un argumento opcional a la función <code>plot</code>:</p>
<pre class="r"><code>plot(height,weight)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<pre class="r"><code>plot(height,weight,pch = 2)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>Algunas funciones no requieren argumentos. Por ejemplo, para mostrar el contenido del espacio de trabajo puedes usar la función <code>ls()</code>.</p>
<blockquote>
<p>Funciones sin argumentos Todas las funciones están seguidas por paréntesis <code>()</code>, aún si estas no requieren de argumentos para ejecutarse.</p>
</blockquote>
</div>
</div>
<div id="vectores" class="section level3">
<h3>Vectores</h3>
<p>Existen tres tipo de vectores:</p>
<ul>
<li>Vectores numéricos.</li>
</ul>
<pre class="r"><code>c(1, 2, 3, 4, 6)</code></pre>
<pre><code>## [1] 1 2 3 4 6</code></pre>
<ul>
<li>Vectores de caracteres.</li>
</ul>
<pre class="r"><code>c(&quot;Huey&quot;, &quot;Dewey&quot;, &quot;Louie&quot;)</code></pre>
<pre><code>## [1] &quot;Huey&quot;  &quot;Dewey&quot; &quot;Louie&quot;</code></pre>
<ul>
<li>Vectores lógicos.</li>
</ul>
<pre class="r"><code>c(TRUE,TRUE,FALSE,TRUE)</code></pre>
<pre><code>## [1]  TRUE  TRUE FALSE  TRUE</code></pre>
<p>Un vector lógico puede ser de resultado de evaluar un operador lógico o una expresión de relación:</p>
<pre class="r"><code>bmi &gt; 25</code></pre>
<pre><code>## [1] FALSE FALSE FALSE FALSE  TRUE FALSE</code></pre>
<p>[1] FALSE FALSE FALSE FALSE TRUE FALSE</p>
<div id="valores-faltantes" class="section level4">
<h4>Valores faltantes</h4>
<p>Es frecuente encontrar bases de datos con valores faltantes. R permite identificar un valor faltante como <code>NA</code> para su posterior manipulación.</p>
</div>
<div id="funciones-que-crean-vectores" class="section level4">
<h4>Funciones que crean vectores</h4>
<p>En ocasiones es útil crear vectores. He aquí algunas funciones:</p>
<ul>
<li><code>c</code>: permite crear un vector especificando los valores de los elementos.</li>
</ul>
<pre class="r"><code>c(42,57,12,19,1,3,4)</code></pre>
<pre><code>## [1] 42 57 12 19  1  3  4</code></pre>
<ul>
<li><code>seq</code>: Crea un secuencia de puntos equidistantes.</li>
</ul>
<pre class="r"><code>seq(4,9)</code></pre>
<pre><code>## [1] 4 5 6 7 8 9</code></pre>
<pre class="r"><code>seq(1.65,1.90,0.05)</code></pre>
<pre><code>## [1] 1.65 1.70 1.75 1.80 1.85 1.90</code></pre>
<ul>
<li><code>4:9</code>: Una sitaxis especial para crear vectores tipo <code>seq(4,9)</code>. El 4 y el 9 son números usados como ejemplo.</li>
</ul>
<pre class="r"><code>4:9</code></pre>
<pre><code>## [1] 4 5 6 7 8 9</code></pre>
<ul>
<li><code>rep</code>: Replica los valores y tiene dos variantes, dependiendo si el segundo argumento es un vector o un escalar.</li>
</ul>
<pre class="r"><code>oops &lt;- c(7,9,13)</code></pre>
<pre class="r"><code>rep(oops,3)</code></pre>
<pre><code>## [1]  7  9 13  7  9 13  7  9 13</code></pre>
</div>
</div>
<div id="ejercicio" class="section level3">
<h3>Ejercicio</h3>
<p>Crea un vector de codificaciones. Los primeros 5 elementos corresponden a alumnos de prepatec, los siguientes 5 de licenciatura y los siguiente 8 de posgrado. Utiliza la función <code>rep</code>.</p>
<blockquote>
<p>Respuesta</p>
<pre class="r"><code>rep(c(1,2,3),c(5,5,8))</code></pre>
<pre><code>##  [1] 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 3 3 3</code></pre>
</blockquote>
</div>
<div id="matrices-y-arreglos" class="section level3">
<h3>Matrices y arreglos</h3>
<blockquote>
<h4 id="matriz">Matriz</h4>
<p>En matemáticas, una matriz es un arreglo <em>numérico</em> de dos dimensiones. En R, este arreglo no se limita a números. Pueden ser incluso <em>cadenas de caracteres</em></p>
</blockquote>
<div id="convierte-un-vector-a-una-matriz" class="section level4">
<h4>Convierte un vector a una matriz</h4>
<p>Usa el comando <code>dim</code>:</p>
<pre class="r"><code>x &lt;- 1:12
dim(x) &lt;- c(3,4)
x</code></pre>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    4    7   10
## [2,]    2    5    8   11
## [3,]    3    6    9   12</code></pre>
<p>La función <code>dim</code> cambia el atributo de dimensiones de <code>x</code>, haciendo que R trate al vector de 12 números como una matriz <span class="math inline">\(3 \times 4\)</span>. Nota la secuencia en que los elementos del vector se acomodan en la matriz, iniciando por el primer elemento de la primer columna de la izquierda.</p>
</div>
<div id="crea-una-matriz-en-menos-pasos" class="section level4">
<h4>Crea una matriz en menos pasos</h4>
<p>Lo anterior se puede simplificar utilizando la función <code>matrix</code> de R:</p>
<pre class="r"><code>matrix(1:12,nrow = 3,byrow = T)</code></pre>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    2    3    4
## [2,]    5    6    7    8
## [3,]    9   10   11   12</code></pre>
<blockquote>
<p>Observa el llenado Nota que ahora al usar <code>byrow = T</code> la matriz se llena siguiendo las filas en lugar de las columnas.</p>
</blockquote>
</div>
<div id="agrega-nombres-a-tus-filas-y-columnas" class="section level4">
<h4>Agrega nombres a tus filas y columnas</h4>
<p>Una característica de R es que te permite personalizar los nombres de las columnas y las filas. Esto es especialmente útil cuando la matrices son muy grandes.</p>
<pre class="r"><code>x &lt;- matrix(1:12,nrow = 3,byrow = T)
rownames(x) &lt;- LETTERS[1:3]</code></pre>
<p>Además de la función <code>LETTERS</code> están <code>letters</code> y <code>month.name</code> que pueden ser de utilidad.</p>
</div>
<div id="trasponer-matrices" class="section level4">
<h4>Trasponer matrices</h4>
<p>Para transponer matrices hay que utilizar la función <code>t</code>:</p>
<pre class="r"><code>t(x)</code></pre>
<pre><code>##      A B  C
## [1,] 1 5  9
## [2,] 2 6 10
## [3,] 3 7 11
## [4,] 4 8 12</code></pre>
</div>
<div id="pegar-reglones-y-columnas" class="section level4">
<h4>Pegar reglones y columnas</h4>
<p>Puedes construir matrices pegando reglones y columnas:</p>
<pre class="r"><code>cbind(A = 1:4, B= 5:8, C = 9:12)</code></pre>
<pre><code>##      A B  C
## [1,] 1 5  9
## [2,] 2 6 10
## [3,] 3 7 11
## [4,] 4 8 12</code></pre>
<pre class="r"><code>rbind(A = 1:4, B= 5:8, C = 9:12)</code></pre>
<pre><code>##   [,1] [,2] [,3] [,4]
## A    1    2    3    4
## B    5    6    7    8
## C    9   10   11   12</code></pre>
</div>
</div>
<div id="factores" class="section level3">
<h3>Factores</h3>
<p>Es común en estadística tener variables categóricas. En ocaciones estas variables tienen nombres o códigos numéricos. En R estas variables se especifican como <em>factores</em>.</p>
<pre class="r"><code>pain &lt;- c(0,3,2,2,1)
fpain &lt;- factor(pain,levels = 0:3)
fpain</code></pre>
<pre><code>## [1] 0 3 2 2 1
## Levels: 0 1 2 3</code></pre>
<pre class="r"><code>levels(fpain) &lt;- c(&quot;none&quot;, &quot;mild&quot;, &quot;medium&quot;, &quot;severe&quot;)
fpain</code></pre>
<pre><code>## [1] none   severe medium medium mild  
## Levels: none mild medium severe</code></pre>
<p>Puedes extraer la codificación numérica de los niveles de los factores</p>
<pre class="r"><code>as.numeric(fpain)</code></pre>
<pre><code>## [1] 1 4 3 3 2</code></pre>
<pre class="r"><code>levels(fpain)</code></pre>
<pre><code>## [1] &quot;0&quot; &quot;1&quot; &quot;2&quot; &quot;3&quot;</code></pre>
<blockquote>
<p>Si no defines los niveles, R lo hará por ti siguiendo el orden alfabético. Sin embargo, hacer esto puede llevar consigo problemas.</p>
<pre class="r"><code>text.pain &lt;- c(&quot;none&quot;, &quot;severe&quot;, &quot;medium&quot;, &quot;medium&quot;, &quot;mild&quot;)
ftext.pain &lt;- factor(text.pain)
ftext.pain</code></pre>
<pre><code>## [1] none   severe medium medium mild  
## Levels: medium mild none severe</code></pre>
<pre class="r"><code>as.numeric(ftext.pain)</code></pre>
<pre><code>## [1] 3 4 1 1 2</code></pre>
</blockquote>
</div>
<div id="listas" class="section level3">
<h3>Listas</h3>
<p>Las listas son colecciones de objetos en un objeto compuesto más grande. Para crearlas se utiliza la función <code>list</code>. Por ejemplo:</p>
<pre class="r"><code>intake.pre &lt;- c(5260, 5470, 5640, 6180, 6390,
+ 6515, 6805, 7515, 7515, 8230, 8770)
intake.post &lt;- c(3910, 4220, 3885, 5160, 5645,
+ 4680, 5265, 5975, 6790, 6900, 7335)
mylist &lt;-list(before = intake.pre, after = intake.post)
mylist</code></pre>
<pre><code>## $before
##  [1] 5260 5470 5640 6180 6390 6515 6805 7515 7515 8230 8770
## 
## $after
##  [1] 3910 4220 3885 5160 5645 4680 5265 5975 6790 6900 7335</code></pre>
<div id="llamando-elementos-de-una-lista" class="section level4">
<h4>Llamando elementos de una lista</h4>
<p>Los componentes de una lista se nombran según los nombres de los argumentos utilizados en la función <code>list</code>. Se pueden extraer usando el operador <code>$</code>:</p>
<pre class="r"><code>mylist$before</code></pre>
<pre><code>##  [1] 5260 5470 5640 6180 6390 6515 6805 7515 7515 8230 8770</code></pre>
</div>
</div>
<div id="data-frame" class="section level3">
<h3>Data Frame</h3>
<p>Un <em>data frame</em> corresponde lo que en estadística se le conoce como una <em>matriz de datos</em> o un <em>conjunto de datos</em>.</p>
<blockquote>
<h4 id="data-frame-1">Data frame</h4>
<p>Es una lista de vectores y/o factores que tiene el mismo largo, y se relacionan transversalmente los unos a los otros. Además, puedes nombrar cada columna de forma única.</p>
</blockquote>
<p>Puede crear data frames de variables existentes:</p>
<pre class="r"><code>d &lt;- data.frame(intake.pre, intake.post)
d</code></pre>
<pre><code>##    intake.pre intake.post
## 1        5260        3910
## 2        5470        4220
## 3        5640        3885
## 4        6180        5160
## 5        6390        5645
## 6        6515        4680
## 7        6805        5265
## 8        7515        5975
## 9        7515        6790
## 10       8230        6900
## 11       8770        7335</code></pre>
<p>Al igual que las listas, la información se puede extraer usando el operador <code>$</code>.</p>
<pre class="r"><code>d$intake.pre</code></pre>
<pre><code>##  [1] 5260 5470 5640 6180 6390 6515 6805 7515 7515 8230 8770</code></pre>
</div>
<div id="indexación" class="section level3">
<h3>Indexación</h3>
<p>Si se requiere de un elemento en particular de un vector se usan corchetes <code>[...]</code>.</p>
<pre class="r"><code>d$intake.pre[5]</code></pre>
<pre><code>## [1] 6390</code></pre>
<p>Si se requieren varios elementos:</p>
<pre class="r"><code>intake.pre[c(3,5,7)]</code></pre>
<pre><code>## [1] 5640 6390 6805</code></pre>
<p>Nota que <code>intake.pre[c(3,5,7)]</code> es distinto a <code>intake.pre[3,5,7]</code>. El segundo indica un indexado en tres dimensiones, y no es el caso que buscamos.</p>
<p>Otra opción es mediante la definición previa del vector:</p>
<pre class="r"><code>v &lt;- c(3,5,7)
intake.pre[v]</code></pre>
<pre><code>## [1] 5640 6390 6805</code></pre>
<pre class="r"><code>intake.pre[1:5]</code></pre>
<pre><code>## [1] 5260 5470 5640 6180 6390</code></pre>
<div id="indices-negativos" class="section level4">
<h4>Indices negativos</h4>
<p>Con R puedes definir qué índice no deseas, y te devolverá el resto:</p>
<pre class="r"><code>intake.pre[-c(3,5,7)]</code></pre>
<pre><code>## [1] 5260 5470 6180 6515 7515 7515 8230 8770</code></pre>
<blockquote>
<h4 id="no-se-mezclan">No se mezclan</h4>
<p>No es posible mezclar índices positivos y negativos en una misma orden.</p>
</blockquote>
</div>
</div>
<div id="selección-condicional" class="section level3">
<h3>Selección condicional</h3>
<p>Anteriormente vimos como extraer información a través del uso de índices. Pero en ocasiones nos interesa únicamente la información que cumpla con cierta regla. Por ejemplo:</p>
<pre class="r"><code>intake.post</code></pre>
<pre><code>##  [1] 3910 4220 3885 5160 5645 4680 5265 5975 6790 6900 7335</code></pre>
<pre class="r"><code>intake.pre &gt; 7000</code></pre>
<pre><code>##  [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE</code></pre>
<pre class="r"><code>intake.post[intake.pre &gt; 7000]</code></pre>
<pre><code>## [1] 5975 6790 6900 7335</code></pre>
<p>El comando <code>intake.pre &gt; 7000</code> genera un vector lógico que es verdadero en los últimos cuatro elementos, y al incluir el vector lógico dentro de otro vector, R regresará los valores donde el vector lógico sea verdadero. Observa que las posiciones obtenidas para este caso son los valores del arreglo <code>intake.post</code> donde <code>intake.pre</code> posee valores mayores a 7000.</p>
<div id="operadores-de-comparación" class="section level4">
<h4>Operadores de comparación</h4>
<p>Los operadores de comparación son:</p>
<ul>
<li><code>&lt;</code>: menor que.</li>
<li><code>&gt;</code>: mayor que.</li>
<li><code>==</code>: igual a. Se usan dos iguales para diferenciar del operador <code>=</code> que es usado para asignar valores.</li>
<li><code>&lt;=</code>: menor o igual que.</li>
<li><code>&gt;=</code>: mayor o igual que.</li>
<li><code>!=</code>: diferente de.</li>
<li><code>&amp;</code>: lógico ``y’’.</li>
<li><code>|</code>: lógico ``0’’.</li>
<li><code>!</code>: lógico ``No’’.</li>
<li><code>&amp;&amp;</code>: lógico ``y también’’.</li>
<li><code>||</code>: lógico ``0 de otra manera’’.</li>
</ul>
<p>El operador <code>&amp;</code> es vectorizado y el operador <code>&amp;&amp;</code> no lo es.</p>
<pre class="r"><code>((-2:2) &gt;= 0) &amp; ((-2:2) &lt;= 0)</code></pre>
<pre><code>## [1] FALSE FALSE  TRUE FALSE FALSE</code></pre>
<pre class="r"><code>((-2:2) &gt;= 0) &amp;&amp; ((-2:2) &lt;= 0)</code></pre>
<pre><code>## [1] FALSE</code></pre>
</div>
<div id="ejemplo-4" class="section level4">
<h4>Ejemplo</h4>
<p>Puedes utilizar operadores lógicos para mejorar tus índices lógicos.</p>
<pre class="r"><code>intake.post[intake.pre &gt; 7000 &amp; intake.pre &lt;= 8000]</code></pre>
<pre><code>## [1] 5975 6790</code></pre>
<p>R regresará aquellos elementos donde el valor lógico sea verdadero (<code>TRUE</code>).</p>
</div>
<div id="valores-faltantes-1" class="section level4">
<h4>Valores faltantes</h4>
<blockquote>
<p>Cuidado con los valores faltantes En caso de que existan valores faltantes, R evaluará la operación lógica, pero en lugar de general un valor de <code>TRUE</code> o <code>FALSE</code> colocará un <code>NA</code>, indicando que existe un valor faltante.</p>
</blockquote>
<p>Para saber si R ha asignado valores faltantes se puede utilizar la función <code>is.na()</code>. La comparación <code>x == NA</code> no es posible, por lo que R la marca como <code>NA</code>. Es decir, la comparación de <code>x</code> con un elemento desconocido es un elemento desconocido.</p>
</div>
<div id="indexar-data-frames" class="section level4">
<h4>Indexar data frames</h4>
<p>La indexación también funciona en los data frames. Se pueden llamar valores como si se tratara de coordenadas en una matriz.</p>
<pre class="r"><code>d &lt;- data.frame(intake.pre, intake.post)
d[5,1]</code></pre>
<pre><code>## [1] 6390</code></pre>
<p>Si deseas obtener todos los valores de un reglón</p>
<pre class="r"><code>d[5,]</code></pre>
<pre><code>##   intake.pre intake.post
## 5       6390        5645</code></pre>
<p>No es lo mismo <code>d[2]</code> a <code>d[,2]</code></p>
<pre class="r"><code>d[2]</code></pre>
<pre><code>##    intake.post
## 1         3910
## 2         4220
## 3         3885
## 4         5160
## 5         5645
## 6         4680
## 7         5265
## 8         5975
## 9         6790
## 10        6900
## 11        7335</code></pre>
<pre class="r"><code>d[,2]</code></pre>
<pre><code>##  [1] 3910 4220 3885 5160 5645 4680 5265 5975 6790 6900 7335</code></pre>
<p>En el primer caso tienes un data frame de una columna, en el segundo un vector.</p>
<p>También puedes usar vectores lógicos para indexar</p>
<pre class="r"><code>d[d$intake.pre &gt; 7000,]</code></pre>
<pre><code>##    intake.pre intake.post
## 8        7515        5975
## 9        7515        6790
## 10       8230        6900
## 11       8770        7335</code></pre>
<p>Recuerda usar la coma para indicar que los valores lógicos se evalúan en la primer columna.</p>
<p>Si sólo deseas ver los primeros elementos del data frame</p>
<pre class="r"><code>d[1:2,]</code></pre>
<pre><code>##   intake.pre intake.post
## 1       5260        3910
## 2       5470        4220</code></pre>
<p>Recuerda usar la coma para indicar que los valores lógicos se evalúan en la primer columna.</p>
<p>También puedes ver los primeros y los últimos elementos del data frame usando las funciones <code>head()</code> y <code>tail()</code></p>
<pre class="r"><code>head(d)</code></pre>
<pre><code>##   intake.pre intake.post
## 1       5260        3910
## 2       5470        4220
## 3       5640        3885
## 4       6180        5160
## 5       6390        5645
## 6       6515        4680</code></pre>
<p>Prueba usar <code>tail()</code> para observar el resultado.</p>
</div>
<div id="pausa-instala-paquete" class="section level4">
<h4>Pausa: instala paquete</h4>
<p>Los siguiente ejercicios los haremos siguiendo bases de datos provistas en el paquete <code>ISwR</code>. Sólo sigue las siguientes instrucciones:</p>
<pre class="r"><code>install.packages(&quot;ISwR&quot;)
library(ISwR)</code></pre>
<p>Ya puedes continuar.</p>
</div>
<div id="datos-agrupados-y-data-frames" class="section level4">
<h4>Datos agrupados y data frames</h4>
<p>Observa los siguientes datos:</p>
<pre class="r"><code>energy</code></pre>
<pre><code>## Warning: package &#39;ISwR&#39; was built under R version 4.0.3</code></pre>
<pre><code>##    expend stature
## 1    9.21   obese
## 2    7.53    lean
## 3    7.48    lean
## 4    8.08    lean
## 5    8.09    lean
## 6   10.15    lean
## 7    8.40    lean
## 8   10.88    lean
## 9    6.13    lean
## 10   7.90    lean
## 11  11.51   obese
## 12  12.79   obese
## 13   7.05    lean
## 14  11.85   obese
## 15   9.97   obese
## 16   7.48    lean
## 17   8.79   obese
## 18   9.69   obese
## 19   9.68   obese
## 20   7.58    lean
## 21   9.19   obese
## 22   8.11    lean</code></pre>
<p>Puedes separar en dos vectores los valores de <code>expend</code> según el factor <code>stature</code>.</p>
<pre class="r"><code>exp.lean &lt;- energy$expend[energy$stature == &quot;lean&quot;]
exp.obese &lt;- energy$expend[energy$stature == &quot;obese&quot;]</code></pre>
<p>O lo puedes hacer en un solo paso con la función <code>split()</code></p>
<pre class="r"><code>split(energy$expend, energy$stature)</code></pre>
<pre><code>## $lean
##  [1]  7.53  7.48  8.08  8.09 10.15  8.40 10.88  6.13  7.90  7.05  7.48  7.58
## [13]  8.11
## 
## $obese
## [1]  9.21 11.51 12.79 11.85  9.97  8.79  9.69  9.68  9.19</code></pre>
</div>
</div>
<div id="ciclos-implícitos" class="section level3">
<h3>Ciclos implícitos</h3>
<p>Se conoce como ciclo a un acción que se repite hasta un número determinado de veces o hasta que se cumple una condición.</p>
<p>Cuando uno programa funciones personalizadas, es común utilizar ciclos explícitos mediante otras funciones como <code>for</code> y <code>while</code>. Sin embargo, su uso requiere control de flujo de datos, lo que incrementa la dificultad y el riesgo de error.</p>
<p>Para facilitar estas operaciones y reducir el grado de error, R proporciona algunas funciones que permiten generar ciclos <em>sencillos</em>. Estas funciones son:</p>
<ul>
<li><code>lapply</code>.</li>
<li><code>sapply</code>.</li>
<li><code>tapply</code>.</li>
<li><code>replicate</code>.</li>
</ul>
<div id="lapply" class="section level4">
<h4><code>lapply</code></h4>
<p>Como ejemplo, para calcular la media.</p>
<pre class="r"><code>lapply(thuesen, mean, na.rm = T)</code></pre>
<pre><code>## $blood.glucose
## [1] 10.3
## 
## $short.velocity
## [1] 1.325652</code></pre>
<p>El primer argumento introducido es data frame, el segundo es la función que se aplicará a cada columna del data frame, el tercer argumento <code>na.rm = T</code> indica a R que ignore los valores faltantes.</p>
</div>
<div id="sapply" class="section level4">
<h4><code>sapply</code></h4>
<p><code>lapply</code> generó los resultados en una lista. Si deseamos los resultados en un vector o matriz, podemos utilizar la función <code>sapply</code>. La <code>s</code> es por simple.</p>
<pre class="r"><code>sapply(thuesen, mean, na.rm = T)</code></pre>
<pre><code>##  blood.glucose short.velocity 
##      10.300000       1.325652</code></pre>
</div>
<div id="replicate" class="section level4">
<h4><code>replicate</code></h4>
<p>Si deseamos realizar una operación un número predeterminado de veces, podemos utilizar la función <code>replicate</code>.</p>
<pre class="r"><code>replicate(10,mean(rexp(20)))</code></pre>
<pre><code>##  [1] 0.7470735 0.9334040 0.6976815 0.9947015 0.8153569 1.2239784 1.3281071
##  [8] 1.0542058 0.8575298 0.7148715</code></pre>
<p>Aquí, el primer argumento indica el número de replicas que deseamos, el segundo argumento es la función que deseamos que se ejecute esa cantidad de veces.</p>
</div>
<div id="apply" class="section level4">
<h4>apply</h4>
<p>Si deseamos trabajar con una matriz, y deseamos realizar una operación por cada columna o reglón, podemos utilizar la función <code>apply</code>.</p>
<pre class="r"><code>m &lt;- matrix(rnorm(12),4)
m</code></pre>
<pre><code>##              [,1]         [,2]       [,3]
## [1,]  1.155336634  0.693681997 -0.7654683
## [2,] -2.024475287  1.801774952 -2.7285706
## [3,]  0.003636907 -0.480212105  0.2260421
## [4,] -1.403672426  0.001477987 -1.1492312</code></pre>
<pre class="r"><code>apply(m,2,min)</code></pre>
<pre><code>## [1] -2.0244753 -0.4802121 -2.7285706</code></pre>
<pre class="r"><code>apply(m,1,min)</code></pre>
<pre><code>## [1] -0.7654683 -2.7285706 -0.4802121 -1.4036724</code></pre>
<p>Aquí, en el primer caso obtenemos el mínimo por columna. En el segundo caso lo obtenemos por reglón.</p>
</div>
<div id="tapply" class="section level4">
<h4><code>tapply</code></h4>
<p><code>tapply</code> se utiliza para aplicar una función a los datos clasificados según un factor.</p>
<pre class="r"><code>tapply(energy$expend,energy$stature,median)</code></pre>
<pre><code>##  lean obese 
##  7.90  9.69</code></pre>
</div>
</div>
<div id="ordenamientos" class="section level3">
<h3>Ordenamientos</h3>
<p>Ordenar los datos es una tarea trivial con la función <code>sort</code>.</p>
<pre class="r"><code>intake$post</code></pre>
<pre><code>##  [1] 3910 4220 3885 5160 5645 4680 5265 5975 6790 6900 7335</code></pre>
<pre class="r"><code>sort(intake.post)</code></pre>
<pre><code>##  [1] 3885 3910 4220 4680 5160 5265 5645 5975 6790 6900 7335</code></pre>
<p>Para ordenar de manera decreciente</p>
<pre class="r"><code>sort(intake.post,decreasing = T)</code></pre>
<pre><code>##  [1] 7335 6900 6790 5975 5645 5265 5160 4680 4220 3910 3885</code></pre>
<div id="obtener-jerarquías" class="section level4">
<h4>Obtener jerarquías</h4>
<p>Las jerarquías son las posiciones relativas en orden ascendente de un conjunto de números. Se pueden obtener con la función <code>order</code>.</p>
<pre class="r"><code>intake$post</code></pre>
<pre><code>##  [1] 3910 4220 3885 5160 5645 4680 5265 5975 6790 6900 7335</code></pre>
<pre class="r"><code>order(intake.post)</code></pre>
<pre><code>##  [1]  3  1  2  6  4  7  5  8  9 10 11</code></pre>
<p>En este caso, el <code>3</code> aparece al principio indicando que el elemento más pequeño se encuentra en la tercer posición. Sigue el <code>1</code>, indicando que el segundo más pequeño está en la primer posición, y así sucesivamente.</p>
</div>
<div id="extender-el-orden-de-una-arreglo-hacia-otros" class="section level4">
<h4>Extender el orden de una arreglo hacia otros</h4>
<p>En ocasiones se requiere ordenar un vector, pero manteniendo la posición relativa de los otros que están relacionados y que son de igual longitud. Para ello ocupamos la extraña forma en que nos indica R las jerarquías con función <code>order</code>.</p>
<pre class="r"><code>o &lt;- order(intake$post)
o</code></pre>
<pre><code>##  [1]  3  1  2  6  4  7  5  8  9 10 11</code></pre>
<pre class="r"><code>intake$post[o]</code></pre>
<pre><code>##  [1] 3885 3910 4220 4680 5160 5265 5645 5975 6790 6900 7335</code></pre>
<pre class="r"><code>intake$pre[o]</code></pre>
<pre><code>##  [1] 5640 5260 5470 6515 6180 6805 6390 7515 7515 8230 8770</code></pre>
<p>Lo anterior se puede hacer directamente en un data frame.</p>
<pre class="r"><code>intake[o,]</code></pre>
<pre><code>##     pre post
## 3  5640 3885
## 1  5260 3910
## 2  5470 4220
## 6  6515 4680
## 4  6180 5160
## 7  6805 5265
## 5  6390 5645
## 8  7515 5975
## 9  7515 6790
## 10 8230 6900
## 11 8770 7335</code></pre>
</div>
</div>
<div id="ejercicios" class="section level3">
<h3>Ejercicios</h3>
<ul>
<li>¿Cómo podrías revisar si dos vectores son iguales cuando pueden contener valore faltantes (<code>NA</code>)? Usar la función <code>identical</code> se considera trampa. Puedes usar la función <code>all</code>, investígala.</li>
</ul>
<pre class="r"><code>(all(A[!is.na(A)] == B[!is.na(B)]) &amp; all(is.na(A)</code></pre>
<ul>
<li>Si <code>x</code> es un factor de <span class="math inline">\(n\)</span> niveles y <code>y</code> es un vector de <span class="math inline">\(n\)</span> elementos, qué pasa si calculas <code>y[x]</code>. Respuesta: Los niveles se representan como números que sirven de entrada como índices.</li>
</ul>
<pre class="r"><code>x = c(&quot;f2&quot;, &quot;f1&quot;, &quot;f3&quot;, &quot;f4&quot;, &quot;f5&quot;)
xfactor &lt;- factor(x,c(c(&quot;f1&quot;, &quot;f2&quot;, &quot;f3&quot;, &quot;f4&quot;, &quot;f5&quot;)))
y[xfactor]</code></pre>
<ul>
<li>Escribe expresiones lógicas para extraer la información de las niñas de entre 7 y 14 años de edad del conjunto de datos <code>juul</code>.</li>
</ul>
<pre class="r"><code>v &lt;- (juul$age &gt;= 7 &amp; juul$age &lt;= 14) &amp; !is.na(juul$age)
juul[v,]</code></pre>
<ul>
<li>¿Qué pasa si cambias los niveles de un factor con la función <code>levels</code> y le das el mismo valor a dos o más niveles? Respuesta: Los valores nombre de todos los factores cambian.</li>
</ul>
<pre class="r"><code>xfactor</code></pre>
<pre class="r"><code>levels(xfactor) &lt;- c(&quot;f1&quot;, &quot;f1&quot;, &quot;f3&quot;, &quot;f4&quot;, &quot;f5&quot;)
xfactor</code></pre>
<ul>
<li>Anteriormente se utilizó la función <code>replicate</code> para obtener la media de 20 números aleatorios generados de una distribución exponencial, y esto se repitió 10 veces. ¿Cómo harías lo mismo utilizando la función <code>apply</code> y <code>sapply</code>?</li>
<li>Usando <code>apply</code></li>
</ul>
<pre class="r"><code>  sim.matrix &lt;- matrix(rexp(10 * 20),20)
  apply(sim.matrix,2,mean)</code></pre>
<pre><code>##  [1] 0.7578647 1.4477881 1.1220723 0.7588689 0.9051068 0.8586334 1.0810790
##  [8] 0.9161116 0.8016943 0.8302115</code></pre>
<ul>
<li>usando <code>sapply</code></li>
</ul>
<pre class="r"><code>sim.matrix &lt;- matrix(rexp(10 * 20),20)
simframe &lt;- data.frame(sim.matrix)
sapply(simframe,mean)</code></pre>
<pre><code>##        X1        X2        X3        X4        X5        X6        X7        X8 
## 1.1776853 0.9999483 1.1082336 0.5394724 1.0374040 0.7739892 0.7840731 0.7357522 
##        X9       X10 
## 0.7798371 0.8373908</code></pre>
</div>
</div>
<div id="ambiente-r" class="section level2">
<h2>Ambiente R</h2>
<div id="descripción-del-módulo" class="section level3">
<h3>Descripción del módulo</h3>
<div id="objetivos" class="section level4">
<h4>Objetivos</h4>
<p>Se discuten algunos aspectos prácticos de trabajar con R. Estructura del entorno de trabajo, creación de gráficas, programación elemental y entrada de datos</p>
</div>
</div>
<div id="administración-de-sesiones" class="section level3">
<h3>Administración de sesiones</h3>
<div id="espacio-de-trabajo" class="section level4">
<h4>Espacio de trabajo</h4>
<p>Todas las variables creadas en <code>R</code> se guardan en un espacio de trabajo común.</p>
<pre class="r"><code>ls()</code></pre>
<pre><code>##  [1] &quot;bmi&quot;         &quot;d&quot;           &quot;exp.lean&quot;    &quot;exp.obese&quot;   &quot;fpain&quot;      
##  [6] &quot;ftext.pain&quot;  &quot;height&quot;      &quot;hh&quot;          &quot;intake.post&quot; &quot;intake.pre&quot; 
## [11] &quot;m&quot;           &quot;mylist&quot;      &quot;o&quot;           &quot;oops&quot;        &quot;pain&quot;       
## [16] &quot;sim.matrix&quot;  &quot;simframe&quot;    &quot;text.pain&quot;   &quot;v&quot;           &quot;weight&quot;     
## [21] &quot;x&quot;           &quot;xbar&quot;</code></pre>
</div>
<div id="remover-variables" class="section level4">
<h4>Remover variables</h4>
<p>Si el espacio de trabajo se ve desordenado, puedes borrar algunos objetos usando <code>rm</code>.</p>
<pre class="r"><code>rm(height,weight)
ls()</code></pre>
<pre><code>##  [1] &quot;bmi&quot;         &quot;d&quot;           &quot;exp.lean&quot;    &quot;exp.obese&quot;   &quot;fpain&quot;      
##  [6] &quot;ftext.pain&quot;  &quot;hh&quot;          &quot;intake.post&quot; &quot;intake.pre&quot;  &quot;m&quot;          
## [11] &quot;mylist&quot;      &quot;o&quot;           &quot;oops&quot;        &quot;pain&quot;        &quot;sim.matrix&quot; 
## [16] &quot;simframe&quot;    &quot;text.pain&quot;   &quot;v&quot;           &quot;x&quot;           &quot;xbar&quot;</code></pre>
</div>
<div id="remover-todas-las-variables" class="section level4">
<h4>Remover todas las variables</h4>
<p>Puedes remover todas las variables usando <code>rm(list=ls())</code>.</p>
<p>Sin embargo, esto no remueve las variables que inicien con un punto, pues estas no se listan en <code>ls()</code>, para eso requieres <code>ls(all=T)</code>.</p>
<blockquote>
<p>Cuidado Remover todas las variables con <code>ls(all=T)</code> puede ser peligroso, pues las variables que inician con un punto son del sistema.</p>
</blockquote>
</div>
<div id="guardar-el-espacio-de-trabajo" class="section level4">
<h4>Guardar el espacio de trabajo</h4>
<p>Puedes guardar todo es espacio de trabajo en un archivo usando la función <code>save.image()</code>.</p>
<p>Esto hará que un archivo <code>.RData</code> se cree en el directorio por defecto.</p>
<p>Usa un nombre entre comillas para asignarle algún nombre en particular a tu sesión y escribir la ruta donde deseas guardar como se muestra a continuación.</p>
<pre class="r"><code>save.image(file = &quot;trabajo.RData&quot;)
load(&quot;trabajo.RData&quot;)
save.image(file = &quot;/home/victor/Documents/R Works/trabajo.RData&quot;)
load(&quot;/home/victor/Documents/R Works/trabajo.RData&quot;)</code></pre>
</div>
<div id="guardar-el-espacio-de-trabajo-1" class="section level4">
<h4>Guardar el espacio de trabajo</h4>
<p>Puedes guardar objetos específicos usando la función <code>save()</code>.</p>
<pre class="r"><code>save(weight,bmi,file = &quot;/home/victor/Documents/RWorks/pesos.RData&quot;)
load(&quot;/home/victor/Documents/R Works/pesos.RData&quot;)</code></pre>
<p>Puedes seleccionar todos los objetos del espacio de trabajo que desees salvar, uno por uno separados por coma. Al final recuerda especificar el nombre para tu archivo de espacio de trabajo junto a su ruta si deseas otra que no sea tu directorio de trabajo.</p>
</div>
<div id="directorio-de-trabajo" class="section level4">
<h4>Directorio de trabajo</h4>
<p>Para ver tu directorio de trabajo actual usa <code>getwd()</code>.</p>
<p>Para modificar tu directorio de trabajo usa <code>setwd()</code>. Ejemplo:</p>
<pre class="r"><code>getwd()
setwd(&quot;/home/victor/Documents/R Works&quot;)
getwd()</code></pre>
</div>
<div id="atención-usuarios-de-windows" class="section level4">
<h4>Atención usuarios de Windows</h4>
<p>R se confunde si escribes una ruta como</p>
<pre class="r"><code>c:\mydocuments\myfile.txt</code></pre>
<p>Esto porque <code>R</code> reconoce <code>\</code> como un caracter de fuga. Para definir tu ruta usa:</p>
<pre class="r"><code>c:\\my documents\\myfile.txt
c:/mydocuments/myfile.txt</code></pre>
</div>
<div id="historial" class="section level4">
<h4>Historial</h4>
<p>Puedes desplegar los últimos 25 comando que escribiste al invocar la función <code>history()</code>. Puedes ver todo el historial con <code>history(max.show=Inf)</code>. Además puedes guardar y leer tu historial usando:</p>
<pre class="r"><code>savehistory(file=&quot;mihistoria&quot;)
loadhistory(file=&quot;myfile&quot;)</code></pre>
<p>Por defecto la extensión de los archivos es <code>.RData</code>.</p>
</div>
<div id="pedir-ayuda" class="section level4">
<h4>Pedir ayuda</h4>
<p>Para pedir ayuda sobre alguna función puedes usar la función <code>help()</code> o simplemente el prefijo <code>?</code> antes de la función de la que deseas pedir ayuda.</p>
<pre class="r"><code>help(&quot;aggregate&quot;)
?aggregate</code></pre>
<p>En ambos casos se logra ingresar a los manuales de ayuda para la función <code>aggregate</code>.</p>
</div>
<div id="paquetes" class="section level4">
<h4>Paquetes</h4>
<p>Una instalación típica de <code>R</code> trae consigo una o más librerías de paquetes. Algunos de estos paquetes son de la instalación básica, y otros pueden ser descargados del <code>CRAN</code> con más de 1000 paquetes para distintos propósitos. <em>¡Incluso puedes crear tus propios paquetes!</em>. Una librería es sólo un fólder en tu disco, mientras que un paquete contiene funciones escritas en el lenguaje <code>R</code>, librerías con códigos (generalmente escritas en <code>C</code> o <code>Fortran</code>), y conjuntos de datos.<br />
</p>
</div>
<div id="paquetes-1" class="section level4">
<h4>Paquetes</h4>
<p>Para cargar un paquete, como el paquete <code>survival</code> usa la función <code>library()</code> y para sacarlo <code>detach</code> de la siguiente manera:</p>
<pre class="r"><code>library(survival)</code></pre>
<pre><code>## 
## Attaching package: &#39;survival&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:ISwR&#39;:
## 
##     lung</code></pre>
<pre class="r"><code>detach(&quot;package:survival&quot;)</code></pre>
<p>Los paquetes no forman parte del espacio de trabajo, por lo que al guardar el espacio y volverlo a cargar tendrás que volver a leer los paquetes que te inreresen.</p>
</div>
<div id="adjunta-data-frames" class="section level4">
<h4>Adjunta data frames</h4>
<p>Puedes adjuntar una copia de las variables de un data frame usando la función <code>attach()</code>:</p>
<pre class="r"><code>attach(thuesen)
blood.glucose</code></pre>
<pre><code>##  [1] 15.3 10.8  8.1 19.5  7.2  5.3  9.3 11.1  7.5 12.2  6.7  5.2 19.0 15.1  6.7
## [16]  8.6  4.2 10.3 12.5 16.1 13.3  4.9  8.8  9.5</code></pre>
<pre class="r"><code>short.velocity</code></pre>
<pre><code>##  [1] 1.76 1.34 1.27 1.47 1.27 1.49 1.31 1.09 1.18 1.22 1.25 1.19 1.95 1.28 1.52
## [16]   NA 1.12 1.37 1.19 1.05 1.32 1.03 1.12 1.70</code></pre>
<p>Con esta función <code>R</code> incluye <code>thuesen</code> en la ruta de búsqueda que puede observase con <code>search()</code>. Usa <code>detach()</code> para sacar las variable copiadas a memoria.</p>
</div>
</div>
</div>
<div id="subsistema-gráfico" class="section level2">
<h2>Subsistema Gráfico</h2>
<div id="descripción-del-módulo-1" class="section level3">
<h3>Descripción del módulo</h3>
<div id="objetivos-1" class="section level4">
<h4>Objetivos</h4>
<p>Es común en estadística querer modificar los gráficos más allá del formato por defecto. En ocasiones se requiere agregar notas, modificar los ejes, cambiar las etiquedas, agregar marcas, etc.</p>
<p>Todo esto se puede hacer en <code>R</code>. Aunque se sienta raro al principio, notarás que el enfoque es flexible y poderoso.</p>
<p>En este módulo se estudiará la estructura de una gráfica típica y se darán indicaciones que te ayuden a lograr los resultados que desees.</p>
<p>Se advierte que el desarrollo de gráficas es una especialidad compleja y amplia cuya profundización va más allá de un curso introductorio.</p>
</div>
</div>
<div id="el-subsistema-de-gráficas" class="section level3">
<h3>El subsistema de gráficas</h3>
<div id="disposición-del-gráfico" class="section level4">
<h4>Disposición del gráfico</h4>
<p>Un gráfico estándar x-y tiene títulos de etiquetas generadas por las expresiones que se grafican. Sin embargo, puedes cambiar estas etiquetas y agregar dos títulos adicionales, un título principal sobre el área gráfica y un subtítulo en la parte inferior.</p>
<pre class="r"><code>x &lt;- runif(50,0,2)
y &lt;- runif(50,0,2)
plot(x, y, main = &quot;Título principal&quot;, sub = &quot;Subtítulo&quot;,
xlab = &quot;Título eje x&quot;, ylab = &quot;Título eje y&quot; )</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-112-1.png" width="672" /></p>
</div>
<div id="agregar-puntos-y-líneas" class="section level4">
<h4>Agregar puntos y líneas</h4>
<p>Dentro de la región de la gráfica puedes agregar puntos y líneas.</p>
<p>Estos los especificas en la función <code>plot</code> o los agregas más tarde con <code>points</code> y <code>lines</code>. También puedes agregar texto con</p>
<pre class="r"><code>text(0.6,0.6,&quot;Texto en punto (0.6,0.6)&quot;)
abline(h = 0.6, v = 0.6)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-114-1.png" width="672" /></p>
</div>
<div id="agregar-texto-en-los-márgenes" class="section level4">
<h4>Agregar texto en los márgenes</h4>
<p>Puedes agregar texto partiendo de las coordenadas de los márgenes. <code>line = -1</code> indica una línea dentro de la figura, <code>line = 1</code>, indica una línea dentro de la figura.</p>
<pre class="r"><code>for (side in 1:4) mtext(-1:4, side = side, at = .7, line = -1:4)
mtext(paste(&quot;side&quot;,1:4), side = 1:4, line = -1, font = 2)</code></pre>
<p>Usando distintas line puedes agregar muchas líneas de texto en cada lado de la figura.</p>
<p><img src="about_files/figure-html/unnamed-chunk-116-1.png" width="672" /></p>
<p>Nota que no todos los márgenes son suficientemente grandes para registrar todos los números, por lo que conviene utilizar posiciones negativas para añadir texto si se desea.</p>
</div>
<div id="contruir-un-gráfico-por-partes" class="section level4">
<h4>Contruir un gráfico por partes</h4>
<p>Para tener más control puedes iniciar un área gráfica en blanco y poco a poco agregar las partes con comandos individuales.</p>
<pre class="r"><code>plot(x, y, type = &quot;n&quot;, xlab = &quot;&quot;, ylab = &quot;&quot;, axes = F)
points(x,y) #agrega los puntos de forma individual
axis(1)
axis(2)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-117-1.png" width="672" /></p>
<pre class="r"><code>plot(x, y, type = &quot;n&quot;, xlab = &quot;&quot;, ylab = &quot;&quot;, axes = F) #prerapa el área de gráfico.
points(x,y) #agrega los puntos de forma individual
axis(1)
axis(2, at =seq(0.2,1.8,0.2))
box()
title(main = &quot;Título principal&quot;, sub = &quot;Subtítulo&quot;, xlab = &quot;Eje x&quot;, ylab = &quot;Eje y&quot;)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-118-1.png" width="672" /></p>
</div>
<div id="función-par" class="section level4">
<h4>Función par</h4>
<p><code>par</code> es una función que permite modificar el grosor de las líneas, el tamaño de los caracteres y su fuente, colres, estilo de ejes, tamaño de las áreas gráficas y regiones de figuras, etc.</p>
<p>Incluso es posible dividir la figura en varias subfiguras usando <code>mfrow</code> y <code>mfcol</code>.</p>
<p>En este momento explicar todos los parámetros gráficos carece de sentido. En su lugar se explicarán cuando se presenten gráficos específicos.</p>
</div>
<div id="combinar-figuras" class="section level4">
<h4>Combinar figuras</h4>
<p>También podemos combinar figuras si así lo deseamos</p>
<pre class="r"><code>x &lt;- rnorm(100) #generamos datos distribución normal
hist(x, freq = F) #creamos un histograma de frecuencias relativas haciendo freq = F
curve(dnorm(x), add = T) #agregamos una curva normal al establecer add = T</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-119-1.png" width="672" /></p>
</div>
<div id="combinar-figuras-1" class="section level4">
<h4>Combinar figuras</h4>
<p>Para asegurar que el histograma y la curva tengan espacio suficiente en la figura, modifica la magnitud de los valores de <code>y</code> en los elementos de ambas gráficas.</p>
<pre class="r"><code>h &lt;- hist(x, plot = F)
ylim &lt;- range(0, h$density, dnorm(0))
hist(x, freq = F, ylim = ylim)
curve(dnorm(x), add = T)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-120-1.png" width="672" /></p>
<p>Al usar en <code>hist</code> el argumento <code>plot = F</code>, <code>hist</code> no despliega nada, pero regresa una estructura que contine las alturas de las barras de las densidades. Esto y el hecho de que el máximo de <code>dnorm(x)</code> es <code>dnorm(0)</code> nor permite calcular el rango que se requiere para los valors de y.</p>
</div>
</div>
</div>
<div id="programación" class="section level2">
<h2>Programación</h2>
<div id="descripción-del-módulo-2" class="section level3">
<h3>Descripción del módulo</h3>
<div id="objetivos-2" class="section level4">
<h4>Objetivos</h4>
<p>Es posible escribir tus propias funciones usando <code>R</code>. Esta posibilidad es principalmente importante al utilizar la aplicación en el largo plazo.</p>
<p>En esta sección veremos estudiaremos las estructura de control que dirigen la ejecución de un programa.</p>
</div>
</div>
<div id="estructuras-de-control" class="section level3">
<h3>Estructuras de control</h3>
<div id="if" class="section level4">
<h4>IF</h4>
<p>La construcción <code>if</code> y <code>else</code> permiten ejecutar o saltar un conjunto de instrucciones dentro del código de un programa de <code>R</code>.</p>
<pre class="r"><code>aa &lt;- 15
if(aa &gt; 14)
 print(&quot;FELICIDADES&quot;)</code></pre>
<pre><code>## [1] &quot;FELICIDADES&quot;</code></pre>
<pre class="r"><code>if(aa &gt; 14) print(&quot;FELICIDADES&quot;)</code></pre>
<pre><code>## [1] &quot;FELICIDADES&quot;</code></pre>
<pre class="r"><code>if(aa &gt; 14){
   print(&quot;PRIMER REGLÓN&quot;)
   print(&quot;SEGUNDO REGLÓN&quot;)
 }</code></pre>
<pre><code>## [1] &quot;PRIMER REGLÓN&quot;
## [1] &quot;SEGUNDO REGLÓN&quot;</code></pre>
<p>Puedes usar el valor que regresa <code>if</code> de forma directa</p>
<pre class="r"><code>y &lt;- 10
y &lt;- if(aa &gt; 14) 50
y</code></pre>
<pre><code>## [1] 50</code></pre>
</div>
<div id="if-else" class="section level4">
<h4>IF-ELSE</h4>
<p>La construcción <code>if</code> admite una sóla expresión, pero ésta puede ser la expresión compuesta, que se construye mediante el uso de llaves <code>{ }</code> y las expresiones en su interior, separadas ya sea por un cambio de reglón o por <code>;</code>.</p>
<p>Para agregar más expresiones en distintas condiciones podemos utilizar la construcción <code>else if</code> y <code>else</code>.</p>
<pre class="r"><code>if(10 &gt; aa){
   print(&quot;RANGO MENOR&quot;)
 } else if(10 &lt;= aa &amp;&amp; aa &lt;= 20){
   print(&quot;RANGO MEDIO&quot;)
 } else{
   print(&quot;RANGO ALTO&quot;)
 }</code></pre>
<pre><code>## [1] &quot;RANGO MEDIO&quot;</code></pre>
</div>
<div id="ciclos" class="section level4">
<h4>Ciclos</h4>
<p>En el lenguaje de programación es común utilizar ciclos o repeticiones. Estas repeticiones implican instrucciones que se repiten un determinado número de veces mientras se cumple una condición.</p>
</div>
<div id="ciclo-for" class="section level4">
<h4>Ciclo FOR</h4>
<pre class="r"><code>letras &lt;- c(&quot;S&quot;, &quot;U&quot;, &quot;A&quot;, &quot;V&quot;, &quot;E&quot;)
for (i in 1:5) {
   print(letras[i])
 }</code></pre>
<pre><code>## [1] &quot;S&quot;
## [1] &quot;U&quot;
## [1] &quot;A&quot;
## [1] &quot;V&quot;
## [1] &quot;E&quot;</code></pre>
<p>La estructura que sigue el ciclo <code>for</code> es:</p>
<pre class="r"><code>for (var in seq) expr</code></pre>
<p>Donde la expresión puede ser compuesta utilizando llaves <code>{ }</code> como en el ejemplo anterior.</p>
<p>Otras formas de lograr el ciclo <code>for</code> es:</p>
<pre class="r"><code>for (i in seq_along(letras)) {
print(letras[i])
}</code></pre>
<pre><code>## [1] &quot;S&quot;
## [1] &quot;U&quot;
## [1] &quot;A&quot;
## [1] &quot;V&quot;
## [1] &quot;E&quot;</code></pre>
<pre class="r"><code>for (letra in letras) {
print(letra)
}</code></pre>
<pre><code>## [1] &quot;S&quot;
## [1] &quot;U&quot;
## [1] &quot;A&quot;
## [1] &quot;V&quot;
## [1] &quot;E&quot;</code></pre>
<p>La función <code>seq_along()</code> genera una secuencia de enteros de acuerdo al número de elementos del objeto usado como argumento.</p>
<p>En el segundo caso se toma uno a uno los elementos del objeto después de la partícula <code>in</code> del <code>for</code>.</p>
</div>
<div id="ciclo-while" class="section level4">
<h4>Ciclo WHILE</h4>
<p>El ejercicio anterior lo podemos lograr utilizando ciclo condicionados al cumplimiento de una regla con la instrucción <code>while</code>.</p>
<pre class="r"><code>i &lt;- 1
while (i &lt;= 5) {
   print(letras[i])
   i &lt;- i + 1
 }</code></pre>
<pre><code>## [1] &quot;S&quot;
## [1] &quot;U&quot;
## [1] &quot;A&quot;
## [1] &quot;V&quot;
## [1] &quot;E&quot;</code></pre>
<p>La instrucción <code>while</code> sigue la estructura</p>
<pre class="r"><code>while (cond) expr</code></pre>
<p>Donde la expresión puede se compuesta al utilizar llaves <code>{ }</code> como se observó en el ejemplo.</p>
</div>
<div id="repeticiones-infinitas" class="section level4">
<h4>Repeticiones infinitas</h4>
<p>La instrucción <code>repeat</code> permite crear ciclos infinitos que no se detienen a menos que agreguemos alguna interrupción como <code>break</code>.</p>
<pre class="r"><code>i &lt;- 1
repeat {
   print(letras[i])
   i &lt;- i + 1
   if (i &gt; 5)
     break
 }</code></pre>
<pre><code>## [1] &quot;S&quot;
## [1] &quot;U&quot;
## [1] &quot;A&quot;
## [1] &quot;V&quot;
## [1] &quot;E&quot;</code></pre>
</div>
<div id="interrupciones-del-flujo-normal-de-los-cilos" class="section level4">
<h4>Interrupciones del flujo normal de los cilos</h4>
<p>Existen funciones como <code>break</code>, <code>next</code> y <code>return</code> que permiten interrumpir los ciclos en el momento en que se ejecutan.</p>
<blockquote>
<p>Advertencia Interrumpir ciclos usando funciones como <code>break</code>, <code>next</code> y <code>return</code> no es recomendado bajo los principios de la programación estructurada.</p>
</blockquote>
<p>Debido a que el uso de estas funciones no es recomendado, no profundizaremos en su uso y aplicación.</p>
</div>
</div>
<div id="escritura-de-funciones" class="section level3">
<h3>Escritura de funciones</h3>
<div id="por-qué-escribir-funciones" class="section level4">
<h4>¿Por qué escribir funciones?</h4>
<p>Cuando el código que escribirmos es muy extenso y complejo, utilizar funciones que nos permitan reciclar nuestros códigos y atender las necesidades en módulos separados de forma ordenada.</p>
</div>
<div id="estructura-formal-de-una-función" class="section level4">
<h4>Estructura formal de una función</h4>
<p>Para crear o definir funciones personalizadas se utiliza la directiva <code>function</code>.</p>
<pre class="r"><code>f &lt;- function(&lt;argumentos&gt;){
  
  #expresiones
  
  &lt;valor&gt; #la última expresión de la lista
}</code></pre>
<p>Esta directiva tiene dos partes:</p>
<ul>
<li>Definición de argumentos formales.</li>
<li>Expresiones.</li>
</ul>
<p>Al ejecutarse la función el valor de la última expresión en la secuencia de ejecución se entrega como resultado</p>
</div>
<div id="ejemplo-de-funciones-caso-1" class="section level4">
<h4>Ejemplo de funciones: Caso 1</h4>
<p>Definimos una función llamada <code>Mifuncion.v1</code> con argumentos <code>x</code>, <code>yyy</code>, <code>z</code>, y <code>t</code>.</p>
<pre class="r"><code>Mifuncion.v1 &lt;- function (x, yyy, z=5, t) {
  w &lt;- x + yyy - z
  w
}
Mifuncion.v1(x = 1, yyy = 2)</code></pre>
<pre><code>## [1] -2</code></pre>
<p><code>x</code>, <code>yyy</code> son argumentos obligatorios. El usuario debe definir su valor al momento de ejecutar la función.</p>
<p><code>z</code> es un argumento opcional, pues si el usuario no lo define, automáticamente toma el valor de 5.</p>
<p><code>t</code> es un argumento adicional que no se emplea en el cuerpo de la función y su definición o falta de ella no afecta el resultado.</p>
<p>Observa el efecto que distintas formas de ejecutar tu función tiene en ella y discute.</p>
<pre class="r"><code>Mifuncion.v1(x = 1, yyy = 2)
Mifuncion.v1(x = 1, yyy = 2, z = 5)
Mifuncion.v1(x = 1, yyy = 2, z = 7)
Mifuncion.v1(x = 1, yyy = 2, z = 7, t = 10)

Mifuncion.v1(1, 2)
Mifuncion.v1(1, 2, 5)
Mifuncion.v1(1, 2, 7)
Mifuncion.v1(1, 2, 7, 10)

Mifuncion.v1(yyy = 2, z = 7, x = 1)
Mifuncion.v1(2, 7, 1)

a = 1
b = 2
c = 3
Mifuncion.v1(x = a, yyy = b, z = c)
Mifuncion.v1(a, b, c)
Mifuncion.v1(a, b, z = c)</code></pre>
</div>
<div id="ejemplo-de-funciones-caso-2" class="section level4">
<h4>Ejemplo de funciones: Caso 2</h4>
<p>Ahora veremos que sucede si agregamos la función <code>return</code> dentro de las expresiones que ejecutará la función que definimos</p>
<pre class="r"><code>Mifuncion.v2 &lt;- function (x, yyy, z=5, t) {
   w &lt;- x + yyy - z
   return (w)
   3.1416 # Este código nunca se ejecuta
 }
Mifuncion.v2(x = 1, yyy = 2)</code></pre>
<pre><code>## [1] -2</code></pre>
<p>La función detiene su ejecución al llegar a <code>return (w)</code> y regresa como resultado el valor del objeto defino entre paréntesis.</p>
</div>
<div id="ejemplo-de-funciones-caso-3" class="section level4">
<h4>Ejemplo de funciones: Caso 3</h4>
<p>Ahora veremos que sucede si el resultado no lo salvas en una variable</p>
<pre class="r"><code>Mifuncion.v3 &lt;- function (x, yyy, z=5, t) {
   x + yyy - z
 }
Mifuncion.v3(x = 1, yyy = 2)</code></pre>
<pre><code>## [1] -2</code></pre>
<p>La función regresa el valor de la última expresión ejecutada, y obtenemos el mismo resultado en en los casos anteriores.</p>
</div>
<div id="variables-locales" class="section level4">
<h4>Variables locales</h4>
<p>Si observamos la variable <code>w</code>, esta se define al moento de ejecutar la función.</p>
<pre class="r"><code>Mifuncion.v1 &lt;- function (x, yyy, z=5, t) {
  w &lt;- x + yyy - z
  w
}</code></pre>
<p><code>w</code> nace en la función y desaparece cuando termina de ejecutarse la función. Se dice que <code>w</code> es una varible local.</p>
</div>
<div id="variables-locales-1" class="section level4">
<h4>Variables locales</h4>
<p>Haz la siguente prueba y observa el resultado</p>
<pre class="r"><code>w &lt;- 9
Mifuncion.v1 &lt;- function (x, yyy, z=5, t) {
   w &lt;- x + yyy - z
   w
 }
Mifuncion.v1(x = 1, yyy = 2)</code></pre>
<pre><code>## [1] -2</code></pre>
<pre class="r"><code>w</code></pre>
<pre><code>## [1] 9</code></pre>
<p>La ejecución de la función no afectó el valor de <code>w</code> definido fuera de ella.</p>
</div>
<div id="vs" class="section level4">
<h4><code>&lt;-</code> vs <code>=</code></h4>
<p>Usar <code>&lt;-</code> para asignar permite que el código sea compatible con códigos y versiones de <code>R</code> viejas.</p>
<p>Asignar con <code>=</code> es una tendencia moderna, y en general se obtiene el mismo efectos que al usar <code>&lt;-</code>. Sin embargo existen diferencias sutiles.</p>
<p>Observa que sucede con el valor de <code>x</code> al definir su valor dentro de los argumentos de una función:</p>
<pre class="r"><code>x = 8
Mifuncion.v1(x = 1, yyy = 2)</code></pre>
<pre><code>## [1] -2</code></pre>
<pre class="r"><code>x</code></pre>
<pre><code>## [1] 8</code></pre>
<pre class="r"><code>Mifuncion.v1(x &lt;- 1, yyy = 2)</code></pre>
<pre><code>## [1] -2</code></pre>
<pre class="r"><code>x</code></pre>
<pre><code>## [1] 1</code></pre>
</div>
<div id="revisión-de-los-argumentos-de-una-función" class="section level4">
<h4>Revisión de los argumentos de una función</h4>
<p>Para revisar los argumentos de una función, ya sea definida por el usuario por o no, podemos utilizar la función <code>args()</code></p>
<pre class="r"><code>args(Mifuncion.v1)</code></pre>
<pre><code>## function (x, yyy, z = 5, t) 
## NULL</code></pre>
<pre class="r"><code>args(lm)</code></pre>
<pre><code>## function (formula, data, subset, weights, na.action, method = &quot;qr&quot;, 
##     model = TRUE, x = FALSE, y = FALSE, qr = TRUE, singular.ok = TRUE, 
##     contrasts = NULL, offset, ...) 
## NULL</code></pre>
<p>Aquí, el estudio del argumento especial <code>...</code> está fuera del alcance del curso, sin embargo el usuario debe saber que se usa para transferir un número variable de argumentos.</p>
</div>
</div>
</div>
<div id="entrada-de-datos" class="section level2">
<h2>Entrada de Datos</h2>
<div id="descripción-del-módulo-3" class="section level3">
<h3>Descripción del módulo</h3>
<div id="objetivos-3" class="section level4">
<h4>Objetivos</h4>
<p>Los conjuntos de datos no tienen que llegar a ser demasiado grandes para que sea impráctico teclearlos usando <code>c(...)</code>. La mayoría de los ejemplos que hemos visto hasta el momento corresponden a bases de datos existentes en el paquete <code>ISwR</code>. Sin embargo, en el momento en que deseamos aplicar estos métodos a nuestros propios datos, tendrás que lidiar con archivos. En esta sección hablaremos sobre cómo leer archivos de datos y como editarlos usando <code>R</code>. Se harán algunas consideraciones para los usuarios de sistemas operativos <strong>Windows</strong>.</p>
</div>
</div>
<div id="entrada-de-datos-1" class="section level3">
<h3>Entrada de datos</h3>
<div id="lectura-de-un-archivo-de-texto" class="section level4">
<h4>Lectura de un archivo de texto</h4>
<p>La forma más conveniente de leer datos en <code>R</code> es a través de la función <code>read.table</code>. Se requiere que los datos estén en <em>formato ASCII</em>; esto es, un <em>archivo plano</em> creado con <strong>NotePad</strong> de <strong>Windows</strong> o cualquier editor de texto plano. El resultado de usar <code>read.table</code> es un data frame, por lo que la función espera encontrar la disposición de datos correspondiente, donde cada línea en el archivo contiene todos los datos de cada sujeto (o rata, o cliente, o…) en un orden específico, separados por espacios en blanco, u opcionalmente, algún otro separador. La primera línea del archivo contiene el encabezado dando los nombre a las variables, una práctica muy recomendada.</p>
</div>
<div id="lee-una-base-de-datos" class="section level4">
<h4>Lee una base de datos</h4>
<pre class="r"><code>thuesenBD &lt;- read.table(&quot;/home//Desktop/thuesenBD.txt&quot;, header = T)</code></pre>
<pre class="r"><code>head(thuesenBD)</code></pre>
<pre><code>##   blood.glucose short.velocity
## 1          15.3           1.76
## 2          10.8           1.34
## 3           8.1           1.27
## 4          19.5           1.47
## 5           7.2           1.27
## 6           5.3           1.49</code></pre>
<p>Recuerda ajustar la ruta del archivo en tu computadora. Descarga el achivo <a href="archivos/thuesenBD.txt">thuesenBD.txt</a>.</p>
</div>
<div id="nota-sobre-windows" class="section level4">
<h4>Nota sobre Windows</h4>
<p>Si usas <strong>Windows</strong> recuerda usar <code>\\</code> o <code>/</code> en lugar de <code>\</code> para separar los directorios.</p>
<pre class="r"><code>N:\\documentos\\thuesenBD.txt
N:/documentos/thuesenBD.txt</code></pre>
</div>
<div id="textos-y-números" class="section level4">
<h4>Textos y números</h4>
<p><code>read.table</code> detecta automáticamente si un vector es numérico y texto, y lo convierte a factor en caso de ser texto. <code>R</code> no intenta reconocer códigos numéricos como factores.</p>
<pre class="r"><code>head(secretinBD)</code></pre>
<pre><code>##   gluc person time repl time20plus time.comb
## 1   92      A  pre    a        pre       pre
## 2   93      A  pre    b        pre       pre
## 3   84      A   20    a        20+        20
## 4   88      A   20    b        20+        20
## 5   88      A   30    a        20+       30+
## 6   90      A   30    b        20+       30+</code></pre>
<p>Descarga el achivo <a href="archivos/secretinBD.txt">secretinBD.txt</a>.</p>
</div>
<div id="textos-y-números-1" class="section level4">
<h4>Textos y números</h4>
<p>Leer factores de esta manera es conveniente, pero hay un punto en contra. Los niveles se leen alfabéticamente.</p>
<pre class="r"><code>levels(secretinBD$time)</code></pre>
<pre><code>## NULL</code></pre>
<p>Si esto no es lo que se desea, tendrás que manipular los niveles de los factores.</p>
</div>
<div id="archivos-delimitados" class="section level4">
<h4>Archivos delimitados</h4>
<p>Las aplicaciones como las hojas de cálculo y bases de datos producen archivos de texto en formatos que requieren que se ajusten múltiples opciones. Para estos propósitos existen variantes de <code>read.table</code> <em>pre-cocinadas</em>. <code>read.csv</code> y <code>read.csv2</code> permiten leer archivos <strong>Csv</strong> separados por coma (<code>,</code>) y punto y coma (<code>;</code>) respectivamente. Ambos asumen <code>header=T</code> por defecto. <code>read.delim</code> y <code>read.delim2</code> ayudan a leer archivos delimitados por tabulaciones. &gt; Recomendación &gt; Usa estas variantes cuando observes que <code>read.table</code> no te da los resultados esperados.</p>
</div>
<div id="conversión-de-datos-entrantes" class="section level4">
<h4>Conversión de datos entrantes</h4>
<p>Por defecto <code>read.table</code> convierte tus datos numéricos como numéricos y los no numéricos como factores. Si por alguna razón esto no tiene sentido puedes revisar los argumentos <code>stringAsFactor</code> para modificar todas las columnas, o <code>as.is</code> para hacerlo de forma individual. La opción <code>colClasses</code> permite espicificar cómo deseas que se lea cada columna, como las clases estándar <code>character</code>, <code>numeric</code>, etc. Si no deseas alguna columna usas <code>NULL</code>.</p>
</div>
<div id="ejemplo-de-conversión-de-datos" class="section level4">
<h4>Ejemplo de conversión de datos</h4>
<p>Si deseas especificar <code>colClasses</code> en <code>read.csv</code> en un conjunto de datos donde la primera columna ``time’’ es un vector de caracteres mientras que las cinco columnas restantes es numérico:</p>
<pre class="r"><code>data &lt;- read.csv(&quot;test.csv&quot;, comment.char=&quot;&quot; , 
                 colClasses=c(&quot;character&quot;,rep(&quot;numeric&quot;,5)), 
                 strip.white=FALSE)</code></pre>
<p>Observa que <code>colClasses</code> debe tener el mismo número de elementos que la cantidad de columnas a importar.</p>
</div>
<div id="editor-de-datos" class="section level4">
<h4>Editor de Datos</h4>
<p><code>R</code> ofrece un editor de texto con una intefaz primitiva de hoja de cálculo, pero muy útil en caso de contar con pequeños conjuntos de datos.</p>
<pre class="r"><code>aq &lt;- edit(airquality)</code></pre>
<p>En este ejemplo, cuando cierras el editor de datos, los datos editados se asignan a la variable <code>aq</code>, mientras que el original <code>airquality</code> permanece intacto.</p>
</div>
<div id="editor-de-datos-1" class="section level4">
<h4>Editor de Datos</h4>
<p>Si no te importa modificar los datos originales puedes usar</p>
<pre class="r"><code>fix(aq)</code></pre>
<p>Esto es equivalente a usar <code>aq &lt;- edit(aq)</code>.</p>
</div>
<div id="editor-de-datos-2" class="section level4">
<h4>Editor de Datos</h4>
<p>Puedes aprovechar el editor para agregar datos manualmente a un dataframe.</p>
<pre class="r"><code>dd &lt;- data.frame()
fix(dd)</code></pre>
<p>Esto es equivalente a usar <code>aq &lt;- edit(aq)</code>.</p>
</div>
<div id="interfaz-con-otros-programas" class="section level4">
<h4>Interfaz con otros programas</h4>
<p>En algunas ocasiones vas a querer extraer datos de otros programas a <code>R</code>.</p>
<p>Por ejemplo, si tienes datos en otros paquetes estadísticos u hojas de cálculo.</p>
<p>Una solución simple a este problema es pedir que el otro programa exporte los datos como un archivo de texto o algún formato compatible con <code>read.table, read.csv, read.csv2, read.delim</code> o <code>read.delim2</code>.</p>
</div>
<div id="paquete-foreign" class="section level4">
<h4>Paquete <code>foreign</code></h4>
<p>El paquete <code>foreign</code> es generalmente etiquetado como ``recomendado’’.</p>
<p>Permite leer archivos de <strong>Spss</strong> (formato <code>.sav</code>), <strong>Sas</strong> (librerías de exportación), <strong>Epi-info</strong> (<code>.rec</code>), <strong>Stata</strong>, <strong>Systat</strong>, <strong>Minitab</strong>, y <strong>S-plus</strong>.</p>
</div>
<div id="leer-del-clipboard" class="section level4">
<h4>Leer del Clipboard</h4>
<p>Una manera rápida de leer datos es usando el Clipboard.</p>
<p>Por ejemplo</p>
<pre class="r"><code>read.table(&quot;clipboard&quot;, header = T)</code></pre>
<p>Esto requiere cierta atención, pues se puede perder la precisión ya que sólo se transfieren los datos que aparecen en pantalla, lo que puede ser un problema si tienes muchos dígitos de significancia.</p>
</div>
<div id="una-nota-para-usuarios-avanzados" class="section level4">
<h4>Una nota para usuarios avanzados</h4>
<p>Para información guardada en bases de datos existe un número de paquetes en el CRAN.</p>
<p>En particular el paquete RODBC te permite configurar una conección ODBC (<em>Open Database Connectivity</em>) para aplicaciones comunes como <strong>Excel</strong> y <strong>Access</strong>.</p>
<p>Para información más actualizada y amplia visita el manual <em>R Data Import/Export</em> en el CRAN.</p>
</div>
</div>
<div id="tareas" class="section level3">
<h3>Tareas</h3>
<div id="ejercicios-1" class="section level4">
<h4>Ejercicios</h4>
<ul>
<li><p>Describe como insertar un valor entre dos elementos de un vector en una posición dada usando la función <code>append</code>. Usa la ayuda del sistema para averiguarlo. ¿Sin <code>append</code> cómo lo harías?</p></li>
<li><p>Escribe la base de datos <code>thuesen</code> en un archivo de texto separado por tabulaciones usando <code>write.table</code>. Revisa la base de datos usando un editor de texto. Cambia los valores <code>NA</code> a <code>.</code> (punto), y lee el archivo modificado de regreso en <code>R</code> con un comando apropiado. También intenta importar los datos de otras aplicaciones de tu elección y expórtalas a un nuevo archivo luego de editarlas. Es posible que tengas que remover los nombres de las columnas para que esto funcione.</p></li>
</ul>
</div>
<div id="ejercicio-1-solución" class="section level4">
<h4>Ejercicio 1: solución</h4>
<pre class="r"><code>?append
x &lt;- c(1,2,3,4,5,6,7) #creamos un vector de prueba
append(x,c(8,9,10),after = length(x)) #agregamos datos al final del vector
append(x,c(8,9,10),after = 4) #agregamos datos después de la cuarta posición

c(x,c(8,9,10)) #agregamos datos al final del vector x
c(x[1:4],c(8,9,10),x[5:7]) #agregamos datos después de la cuarta posición</code></pre>
</div>
<div id="ejercicio-2-solución" class="section level4">
<h4>Ejercicio 2: solución</h4>
<pre class="r"><code>?write.table
write.table(thuesen, file = &quot;Datos.txt&quot;, quote = TRUE, sep = &quot;\t&quot;,
            na = &quot;NA&quot;, row.names = F,
            col.names = TRUE,
            fileEncoding = &quot;&quot;)

#despues de cambiar NA por .

thuesenBD2 &lt;- read.table(&quot;Datos.txt&quot;, header = TRUE,
              sep = &quot;\t&quot;, na.strings = &quot;.&quot;)</code></pre>
<pre class="r"><code># Lee la primera hoja de un documento en miexcel.xlsx
# La primera fila contiene el nombre de las variables
library(xlsx)
mydata &lt;- read.xlsx(&quot;c:/miexcel.xlsx&quot;, 1)

# Lee en la hoja con el nombre mihoja
mydata &lt;- read.xlsx(&quot;c:/miexcel.xlsx&quot;, sheetName = &quot;mihoja&quot;)</code></pre>
</div>
</div>
</div>
<div id="análisis-descriptivo-i" class="section level2">
<h2>Análisis Descriptivo I</h2>
<div id="descripción-del-módulo-4" class="section level3">
<h3>Descripción del módulo</h3>
<div id="objetivos-4" class="section level4">
<h4>Objetivos</h4>
<p>Antes de intentar modelar datos, o hacer inferencias sobre los mismos, lo más sano es explorarlos a través de resúmenes estadísticos y visualizarlos por medio de gráficas diseñadas para ese fin.</p>
<p>A través de ejemplos estaremos explorando algunas estrategias comunes en el análisis de datos.</p>
</div>
</div>
<div id="resúmenes-estadísticos" class="section level3">
<h3>Resúmenes estadísticos</h3>
<div id="estadísticos-simples" class="section level4">
<h4>Estadísticos simples</h4>
<p>Para calcular la media, desviación estándar, varianza y mediana:</p>
<pre class="r"><code>x &lt;- rnorm(50)
mean(x)</code></pre>
<pre><code>## [1] 0.00665102</code></pre>
<pre class="r"><code>sd(x)</code></pre>
<pre><code>## [1] 1.112652</code></pre>
<pre class="r"><code>var(x)</code></pre>
<pre><code>## [1] 1.237994</code></pre>
<pre class="r"><code>median(x)</code></pre>
<pre><code>## [1] 0.03025127</code></pre>
</div>
<div id="más-cuantiles" class="section level4">
<h4>Más Cuantiles</h4>
<p>Cuantiles empíricos se pueden calcular también</p>
<pre class="r"><code>quantile(x)</code></pre>
<pre><code>##          0%         25%         50%         75%        100% 
## -2.45798891 -0.68522589  0.03025127  0.77841802  1.83515444</code></pre>
<p>Cuantiles empíricos se pueden calcular también</p>
<pre class="r"><code>pvec &lt;- seq(0,1,0.1)
pvec</code></pre>
<pre><code>##  [1] 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0</code></pre>
<pre class="r"><code>quantile(x,pvec)</code></pre>
<pre><code>##          0%         10%         20%         30%         40%         50% 
## -2.45798891 -1.52443743 -1.05284459 -0.54157438 -0.37944706  0.03025127 
##         60%         70%         80%         90%        100% 
##  0.49506829  0.69536203  1.01068608  1.53582229  1.83515444</code></pre>
<p>Por defecto <code>R</code> usa interpolación. Existen 7 métodos para calcular cuantiles que se pueden acceder mediante el argumento <code>type</code></p>
</div>
<div id="datos-faltantes" class="section level4">
<h4>Datos faltantes</h4>
<p>Usa los argumentos de las funciones para lidear con datos faltantes.</p>
<pre class="r"><code>attach(juul)
mean(igf1)</code></pre>
<pre><code>## [1] NA</code></pre>
<pre class="r"><code>#Le pedimos a la función ignorar los datos faltantes
mean(igf1,na.rm = T)</code></pre>
<pre><code>## [1] 340.168</code></pre>
</div>
<div id="contar-elementos-cuando-hay-datos-faltantes" class="section level4">
<h4>Contar elementos cuando hay datos faltantes</h4>
<p>La función <code>length</code> no entiende la instrucción <code>na.rm</code>, por lo que no se puede usar para contar la cantidad de datos no faltantes. Para ello se puede usar algo como:</p>
<pre class="r"><code>sum(!is.na(igf1))</code></pre>
<pre><code>## [1] 1018</code></pre>
<p>Los valores <code>TRUE</code> se traducen como <code>1</code> y los <code>FALSE</code> como <code>0</code>. al momento de sumarlos.</p>
</div>
<div id="resumen-de-estadísticos" class="section level4">
<h4>Resumen de estadísticos</h4>
<p>Una resumen de estadísticos de las variables numéricas se puede obtener mediante la función <code>summary</code>.</p>
<pre class="r"><code>summary(igf1)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##    25.0   202.2   313.5   340.2   462.8   915.0     321</code></pre>
</div>
<div id="resumen-de-estadísticos-1" class="section level4">
<h4>Resumen de estadísticos</h4>
<p>También puedes obtener una descripción de todo el data frame.</p>
<pre class="r"><code>summary(juul)</code></pre>
<pre><code>##       age            menarche          sex             igf1      
##  Min.   : 0.170   Min.   :1.000   Min.   :1.000   Min.   : 25.0  
##  1st Qu.: 9.053   1st Qu.:1.000   1st Qu.:1.000   1st Qu.:202.2  
##  Median :12.560   Median :1.000   Median :2.000   Median :313.5  
##  Mean   :15.095   Mean   :1.476   Mean   :1.534   Mean   :340.2  
##  3rd Qu.:16.855   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:462.8  
##  Max.   :83.000   Max.   :2.000   Max.   :2.000   Max.   :915.0  
##  NA&#39;s   :5        NA&#39;s   :635     NA&#39;s   :5       NA&#39;s   :321    
##      tanner        testvol      
##  Min.   :1.00   Min.   : 1.000  
##  1st Qu.:1.00   1st Qu.: 1.000  
##  Median :2.00   Median : 3.000  
##  Mean   :2.64   Mean   : 7.896  
##  3rd Qu.:5.00   3rd Qu.:15.000  
##  Max.   :5.00   Max.   :30.000  
##  NA&#39;s   :240    NA&#39;s   :859</code></pre>
<p>Aquí <code>menarche</code>, <code>sex</code> y <code>tanner</code> están codificadas como numéricas cuando en realidad son categóricas. Podemos corregir esto:</p>
<pre class="r"><code>detach(juul)
juul$sex &lt;- factor(juul$sex, labels = c(&quot;M&quot;,&quot;F&quot;))
juul$menarche &lt;- factor(juul$menarche, labels = c(&quot;No&quot;,&quot;Yes&quot;))
juul$tanner &lt;- factor(juul$tanner, labels = c(&quot;I&quot;, &quot;II&quot;, &quot;III&quot;, &quot;IV&quot;, &quot;V&quot;))
attach(juul)
summary(juul)</code></pre>
<pre><code>##       age         menarche     sex           igf1        tanner   
##  Min.   : 0.170   No  :369   M   :621   Min.   : 25.0   I   :515  
##  1st Qu.: 9.053   Yes :335   F   :713   1st Qu.:202.2   II  :103  
##  Median :12.560   NA&#39;s:635   NA&#39;s:  5   Median :313.5   III : 72  
##  Mean   :15.095                         Mean   :340.2   IV  : 81  
##  3rd Qu.:16.855                         3rd Qu.:462.8   V   :328  
##  Max.   :83.000                         Max.   :915.0   NA&#39;s:240  
##  NA&#39;s   :5                              NA&#39;s   :321               
##     testvol      
##  Min.   : 1.000  
##  1st Qu.: 1.000  
##  Median : 3.000  
##  Mean   : 7.896  
##  3rd Qu.:15.000  
##  Max.   :30.000  
##  NA&#39;s   :859</code></pre>
<p>Nota como cambia la presentación de los datos categóricos.</p>
<p>Las modificaciones al data frame no afectan la versión adjunta con <code>attach</code>, por eso del <code>detach</code> usado.</p>
</div>
<div id="función-transform-o-within" class="section level4">
<h4>Función <code>transform</code> o <code>within</code></h4>
<p>Para ajustar varias variables dentro de un data frame puedes usar:</p>
<pre class="r"><code>juul &lt;- transform(juul,
                   sex = factor(sex, labels = c(&quot;M&quot;,&quot;F&quot;)),
                   menarche = factor(menarche, labels = c(&quot;No&quot;,&quot;Yes&quot;)),
                   tanner = factor(tanner, labels = c(&quot;I&quot;, &quot;II&quot;, &quot;III&quot;, &quot;IV&quot;, &quot;V&quot;)))</code></pre>
<p>Recuerda usar comas para separar cada modificación.</p>
</div>
</div>
<div id="gráficas-1" class="section level3">
<h3>Gráficas</h3>
<div id="histogramas" class="section level4">
<h4>Histogramas</h4>
<p>Puedes crear histogramas con la función <code>hist()</code></p>
<pre class="r"><code>x = rnorm(1000)
hist(x)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-176-1.png" width="672" /></p>
<p>Controla el número de clases con <code>breaks = n</code>.</p>
<pre class="r"><code>hist(x, breaks = 5)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-177-1.png" width="672" /></p>
</div>
<div id="histogramas-1" class="section level4">
<h4>Histogramas</h4>
<p>También puedes especificar los límites de los intervalos de clase con el mismo argumento <code>breaks</code> al definirlo como vector.</p>
<p>Usemos como ejemplo los datos de accidentes por grupo de edad documentados por Altman (1991):</p>
<pre class="r"><code>mid.age &lt;- c(2.5,7.5,13,16.5,17.5,19,22.5,44.5,70.5)
acc.count &lt;- c(28,46,58,20,31,64,149,316,103)
age.acc &lt;- rep(mid.age,acc.count)
brk &lt;- c(0,5,10,16,17,18,20,25,60,80)
hist(age.acc,breaks = brk)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-178-1.png" width="672" /></p>
<p>Nota que automáticamente el histograma corrige el área de la columna para hacerla proporcional a la cantidad de elementos en ella.</p>
</div>
<div id="distribución-acumulada-empírica" class="section level4">
<h4>Distribución acumulada empírica</h4>
<p>La distribución acumulada se define como la fracción de datos menores o iguales a <span class="math inline">\(x\)</span>. Esto es, si <span class="math inline">\(x\)</span> es la <span class="math inline">\(k\)</span>-ésima observación más pequeña, la proporción <span class="math inline">\(k/n\)</span> de los datos son menores o iguales a <span class="math inline">\(x\)</span>. Así, la distriución empírica puede ser graficada como</p>
<pre class="r"><code>n &lt;- length(x)
plot(sort(x), (1:n)/n, xlab=&quot;x&quot;,
     ylab=&quot;Proporción&quot;, type = &quot;s&quot;, ylim = c(0,1))</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-179-1.png" width="672" /></p>
<p>Usar <code>type = "s"</code> crea una función escalonada.</p>
</div>
<div id="graficas-cuantil-cuantil" class="section level4">
<h4>Graficas Cuantil-Cuantil</h4>
<p>Una de las razones para construir la distribución empírica acumulada es para verificar si los datos siguen una distribución normal. Para una mejor evaluación de este hecho podemos ocupar las gráficas cuantil-cuantil</p>
<pre class="r"><code>qqnorm(x)</code></pre>
<p><img src="about_files/figure-html/e-1.png" width="672" /></p>
<p>Si los datos siguen una distribución normal, las gráfica cuantil-cuantil deberá mostrar aproximadamente una línea recta.</p>
</div>
<div id="gráfica-de-cajas" class="section level4">
<h4>Gráfica de cajas</h4>
<p>Una gráfica de cajas, o gráfica de cajas y bigotes, brinda una visión de los datos y permite su rápida comparación. Además, nos ayuda a detectar si existen puntos atípicos en las observaciones que puedan requerir atención especial.</p>
<pre class="r"><code>par(mfrow=c(1,2))
boxplot(IgM)
boxplot(log(IgM))</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-180-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow=c(1,1))</code></pre>
<p>La función <code>par()</code> permite controlar los parámetros globales del ambiente gráfico. Uno de estos parámetros globales es <code>mfrow</code>, que se lee <code>multiframe, rowwise</code>. <code>c(1,2)</code> define una fila con dos columnas para acomodar figuras.</p>
<blockquote>
<p>Nota sobre la función par La función par afecta los parámetros de maner global, por lo que es necesario indicarle a <code>R</code> que luego de crear la figura regrese los parámetros a su estado por defecto.</p>
</blockquote>
<p>En el ejemplo anterior. Después de crear dos figuras en una misma área tuvimos que ejecutar nuevamente el comando <code>par(mfrow=c(1,1))</code> para reestablecer la configuración inicial (a menos que desees mantenerla para siguientes gráficas).</p>
</div>
</div>
<div id="resúmenes-estadísticos-por-grupo" class="section level3">
<h3>Resúmenes estadísticos por grupo</h3>
<ul>
<li>Estadísticas por grupos Cuando se trabaja con datos agrupados, es muy común querer obtener resúmenes estadísticos de los mismos dentro de cada grupo.</li>
</ul>
<p>Por ejemplo, una tabla de medias y desviaciones estándar.</p>
<p>Para este fin usaremos <code>apply</code>.</p>
<ul>
<li>Medias</li>
</ul>
<pre class="r"><code>tapply(folate,ventilation,mean)</code></pre>
<ul>
<li>Desviaciones</li>
</ul>
<pre class="r"><code>tapply(folate,ventilation,sd)</code></pre>
<ul>
<li>Conteos</li>
</ul>
<pre class="r"><code>tapply(folate,ventilation,length)</code></pre>
<ul>
<li>Junta varios resultados} Si quieres que se vea más bonito prueba lo siguiente:</li>
</ul>
<pre class="r"><code>cbind(media = xbar, desv.est = s, n = n)</code></pre>
<ul>
<li>Valores faltantes Si tienes valores faltantes por defecto no se analizan</li>
</ul>
<pre class="r"><code>attach(juul)</code></pre>
<pre><code>## The following objects are masked from juul (pos = 3):
## 
##     age, igf1, menarche, sex, tanner, testvol</code></pre>
<pre class="r"><code>tapply(igf1,tanner,mean)</code></pre>
<pre><code>##   I  II III  IV   V 
##  NA  NA  NA  NA  NA</code></pre>
<p>Modifica el argumento <code>na.rm=T</code></p>
<pre class="r"><code>tapply(igf1,tanner,mean, na.rm=T)</code></pre>
<pre><code>##        I       II      III       IV        V 
## 207.4727 352.6714 483.2222 513.0172 465.3344</code></pre>
<div id="otras-opciones-aggregate" class="section level4">
<h4>Otras opciones: aggregate</h4>
<p><code>aggregate</code> y <code>by</code> son variaciones de lo mismo ya visto, salvo que el primero funciona para todo el data frame y presenta los resultados en un data frame.</p>
<p>Muy útil para presentar varios resultados a la vez.</p>
<pre class="r"><code>aggregate(juul[c(&quot;age&quot;,&quot;igf1&quot;)],
           list(sex=juul$sex), mean, na.rm=T)</code></pre>
<pre><code>##   sex      age     igf1
## 1   M 15.38436 310.8866
## 2   F 14.84363 368.1006</code></pre>
<p>Nota que el argumento que agrupa debe estar contenido en una lista siempre.</p>
<p>La variable índice no necesariamente forma parte del data frame evaluado, por lo que hay que incluir toda su ruta como <code>juul$sex</code>.</p>
<p>En este caso, puesto que un data frame es en realidad una lista:</p>
<pre class="r"><code>aggregate(juul[c(&quot;age&quot;,&quot;igf1&quot;)],juul[&quot;sex&quot;], mean, na.rm=T)</code></pre>
<pre><code>##   sex      age     igf1
## 1   M 15.38436 310.8866
## 2   F 14.84363 368.1006</code></pre>
<p>El truco está en que el indice, al estar entre corchetes, regresa un data frame.</p>
</div>
<div id="otras-opciones-by" class="section level4">
<h4>Otras opciones: by</h4>
<p>Puedes hacer los mismo con la función by</p>
<pre class="r"><code>by(juul$age, juul[&quot;sex&quot;], mean, na.rm=T)</code></pre>
<pre><code>## sex: M
## [1] 15.38436
## ------------------------------------------------------------ 
## sex: F
## [1] 14.84363</code></pre>
<p>Si quieres un resumen de todas las variables</p>
<pre class="r"><code>by(juul, juul[&quot;sex&quot;], summary)</code></pre>
<pre><code>## sex: M
##       age        menarche   sex          igf1        tanner       testvol      
##  Min.   : 0.17   No  :  0   M:621   Min.   : 29.0   I   :291   Min.   : 1.000  
##  1st Qu.: 8.85   Yes :  0   F:  0   1st Qu.:176.0   II  : 55   1st Qu.: 1.000  
##  Median :12.38   NA&#39;s:621           Median :280.0   III : 34   Median : 3.000  
##  Mean   :15.38                      Mean   :310.9   IV  : 41   Mean   : 7.896  
##  3rd Qu.:16.77                      3rd Qu.:430.2   V   :124   3rd Qu.:15.000  
##  Max.   :83.00                      Max.   :915.0   NA&#39;s: 76   Max.   :30.000  
##                                     NA&#39;s   :145                NA&#39;s   :141     
## ------------------------------------------------------------ 
## sex: F
##       age        menarche   sex          igf1        tanner       testvol   
##  Min.   : 0.25   No  :369   M:  0   Min.   : 25.0   I   :224   Min.   : NA  
##  1st Qu.: 9.30   Yes :335   F:713   1st Qu.:233.0   II  : 48   1st Qu.: NA  
##  Median :12.80   NA&#39;s:  9           Median :352.0   III : 38   Median : NA  
##  Mean   :14.84                      Mean   :368.1   IV  : 40   Mean   :NaN  
##  3rd Qu.:16.93                      3rd Qu.:483.0   V   :204   3rd Qu.: NA  
##  Max.   :75.12                      Max.   :914.0   NA&#39;s:159   Max.   : NA  
##                                     NA&#39;s   :176                NA&#39;s   :713</code></pre>
<p>Cuyo resultado ahora es en forma de lista.</p>
</div>
</div>
<div id="gráficas-para-datos-agrupados" class="section level3">
<h3>Gráficas para datos agrupados</h3>
<div id="histogramas-2" class="section level4">
<h4>Histogramas</h4>
<p>Veamos algunos ejemplos. Primero adjuntemos los datos del data frame <code>energy</code>.</p>
<pre class="r"><code>attach(energy)
expend.lean &lt;- expend[stature == &quot;lean&quot;]
expend.obese &lt;- expend[stature == &quot;obese&quot;]</code></pre>
<p>Ahora hagamos histogramas.</p>
<pre class="r"><code>par(mfrow = c(2,1))
hist(expend.lean, breaks = 10, xlim = c(5,13),
      ylim = c(0,4), col = &quot;white&quot;)
 hist(expend.obese, breaks = 10, xlim = c(5,13),
      ylim = c(0,4), col = &quot;grey&quot;)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-192-1.png" width="672" /></p>
<pre class="r"><code> par(mfrow =c(1,1))</code></pre>
</div>
<div id="gráficas-de-caja-paralelas" class="section level4">
<h4>Gráficas de caja paralelas</h4>
<p>Usa el comando</p>
<pre class="r"><code>boxplot(expend ~ stature, col = c(&quot;red&quot;, &quot;blue&quot;))</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-193-1.png" width="672" /></p>
<p>También pudimos haber creado el diagrama con el comando <code>boxplot(expend.lean, expend.obese)</code>.</p>
</div>
<div id="diagrama-de-puntos" class="section level4">
<h4>Diagrama de puntos</h4>
<p>Cuando se tienen pocos datos, como en el ejemplo anterior, el cálculo del intervalo intercuartílico (largo de la caja) es poco preciso y nuestros gráficos pueden sufrir del efecto del .</p>
<p>Cuando tenemos pocos datos puede ser más conveniente utilizar un diagrama de observaciones individuales donde cada observación es graficada como un punto en el eje.</p>
<p>Para lograr esto usamos la función <code>stripchart</code>.</p>
</div>
<div id="diagrama-de-observaciones-individuales" class="section level4">
<h4>Diagrama de observaciones individuales</h4>
<pre class="r"><code>opar &lt;- par(mfrow = c(2,2), mex=0.6, mar=c(3,3,2,1)+0.1)
stripchart(expend ~ stature)
stripchart(expend ~ stature, method = &quot;stack&quot;)
stripchart(expend ~ stature, method = &quot;jitter&quot;)
stripchart(expend ~ stature, method = &quot;jitter&quot;, jitter=0.03)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-194-1.png" width="672" /></p>
<pre class="r"><code>par(opar)</code></pre>
<blockquote>
<p>Algunas observaciones sobre la función <code>par</code> * La configuración original de par se guarda en una variable (opar). * La configuración original se reestablece con <code>par(opar)</code> * El argumento <code>mex</code> reduce la distancia entre líneas. * <code>mar</code> reduce el número de líneas que rodean la región de la gráfica.</p>
</blockquote>
<blockquote>
<p>Algunas observaciones sobre los argumentos de <code>stripchart</code> * La versión por defecto gráfica los puntos sobre la línea, que puede ser problemático si hay traslapes. * El argumento <code>method="stack"</code> apila las observaciones iguales. Lo que puede ser todavía un problema con las casi iguales. * <code>method="jitter"</code> crea una pequeña perturbación aleatoria que separa los puntos en un eje imaginario. * Por defecto <code>jitter</code> está definido en <code>0.1</code>, lo que puede ser mucha perturbación para algunos. Usar <code>jitter = 0.03</code> permite ajustar esto a valores menores.</p>
</blockquote>
</div>
</div>
</div>
<div id="análisis-descriptivo-ii" class="section level2">
<h2>Análisis Descriptivo II</h2>
<div id="descripción-del-módulo-5" class="section level3">
<h3>Descripción del módulo</h3>
<div id="objetivos-5" class="section level4">
<h4>Objetivos</h4>
<p>Los datos categóricos usualmente se describen en forma de tablas.</p>
<p>En esta sección se presentan algunas estrategias para crearlas a partir de tus datos y algunas gráficas comunes para su visualización.</p>
</div>
</div>
<div id="tablas" class="section level3">
<h3>Tablas</h3>
<div id="generación-de-tablas" class="section level4">
<h4>Generación de tablas</h4>
<p>Lideamos principalmente con tablas de dos dimensiones.</p>
<p>Estas pueden ser creadas a partir de una matriz.</p>
<p>De Altman (1991):</p>
<pre class="r"><code>caff.marital &lt;- matrix(c(652, 1537, 598, 242, 36, 46, 38,
                          21, 218, 327, 106, 67),
                        nrow = 3, byrow = T)
caff.marital</code></pre>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]  652 1537  598  242
## [2,]   36   46   38   21
## [3,]  218  327  106   67</code></pre>
<p>Para hacer la tabla es necesario definir los nombre a las columnas y los reglones</p>
<pre class="r"><code>colnames(caff.marital) &lt;- c(&quot;0&quot;, &quot;1-150&quot;, &quot;151-300&quot;, &quot;&gt;300&quot;)
rownames(caff.marital) &lt;- c(&quot;Casados&quot;, &quot;Divorciados&quot;, &quot;Solteros&quot;)
caff.marital</code></pre>
<pre><code>##               0 1-150 151-300 &gt;300
## Casados     652  1537     598  242
## Divorciados  36    46      38   21
## Solteros    218   327     106   67</code></pre>
<p>También puedes renombrar las dimensiones de la matriz.</p>
<pre class="r"><code>caff.marital</code></pre>
<pre><code>##               0 1-150 151-300 &gt;300
## Casados     652  1537     598  242
## Divorciados  36    46      38   21
## Solteros    218   327     106   67</code></pre>
</div>
<div id="clase-table" class="section level4">
<h4>Clase <code>table</code></h4>
<p>Las tablas no son completamente equivalentes a matrices. En <code>R</code> existe una clase llamada <code>table</code> que puedes acceder por medio de <code>as.table()</code>.</p>
<pre class="r"><code>table.caff.marital &lt;- as.table(caff.marital)
table.caff.marital</code></pre>
<pre><code>##                0 1-150 151-300 &gt;300
## Casados      652  1537     598  242
## Divorciados   36    46      38   21
## Solteros     218   327     106   67</code></pre>
<p>Si no requieres hacer nada elaborado, usar matrices o usar tablas te darán el mismo resultado, como se observa en el ejemplo.</p>
<p>Tener un objeto de clase <code>table</code> es útil cuando deseamos hacer algo más elaborado, como convertir una tabla en un data frame.</p>
<pre class="r"><code>as.data.frame(table.caff.marital)</code></pre>
<pre><code>##           Var1    Var2 Freq
## 1      Casados       0  652
## 2  Divorciados       0   36
## 3     Solteros       0  218
## 4      Casados   1-150 1537
## 5  Divorciados   1-150   46
## 6     Solteros   1-150  327
## 7      Casados 151-300  598
## 8  Divorciados 151-300   38
## 9     Solteros 151-300  106
## 10     Casados    &gt;300  242
## 11 Divorciados    &gt;300   21
## 12    Solteros    &gt;300   67</code></pre>
</div>
<div id="crear-tablas-a-partir-de-data-frames" class="section level4">
<h4>Crear tablas a partir de data frames</h4>
<p>Recordemos el ajuste que hicimos al data frame <code>juul</code>.</p>
<pre class="r"><code>juul &lt;- transform(juul,
                  sex = factor(sex, labels = c(&quot;M&quot;,&quot;F&quot;)),
                  menarche = factor(menarche, labels = c(&quot;No&quot;,&quot;Yes&quot;)),
                  tanner = factor(tanner, labels = c(&quot;I&quot;, &quot;II&quot;, &quot;III&quot;,
                                  &quot;IV&quot;, &quot;V&quot;)))</code></pre>
<p>Creamos ahora algunas tablas con la función <code>table()</code>.</p>
<pre class="r"><code>table(juul$sex)</code></pre>
<pre><code>## 
##   M   F 
## 621 713</code></pre>
<p>Algunos otros ejemplos</p>
<pre class="r"><code>table(juul$sex, juul$menarche)</code></pre>
<pre><code>##    
##      No Yes
##   M   0   0
##   F 369 335</code></pre>
<pre class="r"><code>table(juul$menarche, juul$tanner)</code></pre>
<pre><code>##      
##         I  II III  IV   V
##   No  221  43  32  14   2
##   Yes   1   1   5  26 202</code></pre>
</div>
<div id="más-de-dos-dimensiones" class="section level4">
<h4>Más de dos dimensiones</h4>
<p>Si queremos una tabla con más de dos dimensiones</p>
<pre class="r"><code>table(juul$menarche, juul$tanner, juul$sex)</code></pre>
<pre><code>## , ,  = M
## 
##      
##         I  II III  IV   V
##   No    0   0   0   0   0
##   Yes   0   0   0   0   0
## 
## , ,  = F
## 
##      
##         I  II III  IV   V
##   No  221  43  32  14   2
##   Yes   1   1   5  26 202</code></pre>
<p>La función <code>table()</code> sigue funcionando, pero el resultado es poco estético</p>
</div>
<div id="función-xtabs" class="section level4">
<h4>Función xtabs</h4>
<p>Podemos intentarlo con la función <code>xtabs</code>:</p>
<pre class="r"><code>xtabs(~ tanner + sex, data =juul)</code></pre>
<pre><code>##       sex
## tanner   M   F
##    I   291 224
##    II   55  48
##    III  34  38
##    IV   41  40
##    V   124 204</code></pre>
<p>La ventaja es que podemos nombrar las variables dentro del data frame sin tener que utilizar <code>$</code>.</p>
<p>Si son más de dos dimensiones:</p>
<pre class="r"><code>xtabs(~ menarche +  tanner + sex, data =juul)</code></pre>
<pre><code>## , , sex = M
## 
##         tanner
## menarche   I  II III  IV   V
##      No    0   0   0   0   0
##      Yes   0   0   0   0   0
## 
## , , sex = F
## 
##         tanner
## menarche   I  II III  IV   V
##      No  221  43  32  14   2
##      Yes   1   1   5  26 202</code></pre>
<p>Seguimos teniendo resultados poco estéticos.</p>
</div>
<div id="función-ftable" class="section level4">
<h4>Función ftable</h4>
<p>Ahora tratamos con la función <code>ftable</code>:</p>
<pre class="r"><code>ftable(tanner~menarche + sex, data =juul)</code></pre>
<pre><code>##              tanner   I  II III  IV   V
## menarche sex                           
## No       M            0   0   0   0   0
##          F          221  43  32  14   2
## Yes      M            0   0   0   0   0
##          F            1   1   5  26 202</code></pre>
<p>El resultado es mucho más estético.</p>
</div>
<div id="transponer-una-tabla" class="section level4">
<h4>Transponer una tabla</h4>
<p>Para transponer una tabla usamos el mismo comando <code>t()</code> que usamos para transponer matrices.</p>
<pre class="r"><code>table.caff.marital</code></pre>
<pre><code>##                0 1-150 151-300 &gt;300
## Casados      652  1537     598  242
## Divorciados   36    46      38   21
## Solteros     218   327     106   67</code></pre>
<pre class="r"><code>t(table.caff.marital)</code></pre>
<pre><code>##         Casados Divorciados Solteros
## 0           652          36      218
## 1-150      1537          46      327
## 151-300     598          38      106
## &gt;300        242          21       67</code></pre>
</div>
</div>
<div id="tablas-marginales-y-frecuencias-relativas" class="section level3">
<h3>Tablas marginales y frecuencias relativas</h3>
<div id="tablas-marginales" class="section level4">
<h4>Tablas marginales</h4>
<p>En ocasiones es deseable obtener los valores marginales de las tablas, esto es, las sumas de los conteos sobre una u otra dimensión en la tabla algo similar a lo que se obtiene en MS Excel con la opción de subtotales, pero restringidoa conteos.</p>
<p>Esto se puede lograr con la opción <code>apply</code>, sin embargo, existe una función todavía más simplificada llamada <code>margin.table</code>.</p>
</div>
<div id="función-margin.table" class="section level4">
<h4>Función <code>margin.table</code></h4>
<p>Del paquete <code>ISwR</code> creamos una tabla con el data frame <code>juul</code>. Revisa si el data frame lo tienes adjunto a la ruta de búsqueda de <code>R</code> con <code>search()</code>. Para adjuntarlo ejecuta el comando <code>attach(juul)</code>, para retirarlo de la ruta usa <code>detach(juul)</code></p>
<pre class="r"><code>tanner.sex &lt;- table(tanner,sex)
tanner.sex</code></pre>
<pre><code>##       sex
## tanner   M   F
##    I   291 224
##    II   55  48
##    III  34  38
##    IV   41  40
##    V   124 204</code></pre>
</div>
<div id="función-margin.table-1" class="section level4">
<h4>Función <code>margin.table</code></h4>
<p>Ahora obtén los conteos marginales de la tabla usando <code>margin.table()</code>.</p>
<pre class="r"><code>margin.table(tanner.sex,1)</code></pre>
<pre><code>## tanner
##   I  II III  IV   V 
## 515 103  72  81 328</code></pre>
<pre class="r"><code>margin.table(tanner.sex,2)</code></pre>
<pre><code>## sex
##   M   F 
## 545 554</code></pre>
<p>El <code>1</code> indica los reglones y el <code>2</code> las columnas.</p>
</div>
<div id="frecuencias-relativas" class="section level4">
<h4>Frecuencias relativas</h4>
<p>Obtén las frecuencias relativas mediante <code>prop.table()</code>.</p>
<pre class="r"><code>prop.table(tanner.sex, margin = 1)</code></pre>
<pre><code>##       sex
## tanner         M         F
##    I   0.5650485 0.4349515
##    II  0.5339806 0.4660194
##    III 0.4722222 0.5277778
##    IV  0.5061728 0.4938272
##    V   0.3780488 0.6219512</code></pre>
<p>El <code>1</code> indica los reglones y el <code>2</code> las columnas.</p>
<p>Si deseas los porcentajes, sólo multiplica la tabla por 100.</p>
<p>La función <code>prop.table()</code> no puede darte las frecuencias relativas al gran total. Si esto es lo que deseas siempre puedes dividir la tabla entre el gran total.</p>
<pre class="r"><code>tanner.sex / sum(tanner.sex)</code></pre>
<pre><code>##       sex
## tanner          M          F
##    I   0.26478617 0.20382166
##    II  0.05004550 0.04367607
##    III 0.03093722 0.03457689
##    IV  0.03730664 0.03639672
##    V   0.11282985 0.18562329</code></pre>
</div>
</div>
<div id="resúmenes-gráficos-para-tablas" class="section level3">
<h3>Resúmenes gráficos para tablas</h3>
<div id="gráficas-de-barras" class="section level4">
<h4>Gráficas de barras</h4>
<p>Al momento de hacer presentaciones, puede ser preferible utilizar una gráfica a presentar un grupo de totales y proporciones.</p>
<pre class="r"><code>total.caff &lt;- margin.table(table.caff.marital, 2)
total.caff</code></pre>
<pre><code>##       0   1-150 151-300    &gt;300 
##     906    1910     742     330</code></pre>
<pre class="r"><code>barplot(total.caff, col = &quot;green&quot;)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-216-1.png" width="672" /></p>
<p>Al momento de hacer presentaciones, puede ser preferible utilizar una gráfica a presentar un grupo de totales y proporciones.</p>
<pre class="r"><code>total.caff &lt;- margin.table(table.caff.marital, 2)
total.caff</code></pre>
<pre><code>##       0   1-150 151-300    &gt;300 
##     906    1910     742     330</code></pre>
<pre class="r"><code>barplot(total.caff, col = &quot;green&quot;, ylim = c(0,2000))</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-218-1.png" width="672" /></p>
<p>Aquí, <code>ylim = c(0,2000)</code> es el rango a utilizar en el eje de las ordenadas.</p>
<p>La función <code>barplot</code> también te acepta la tabla completa.</p>
<pre class="r"><code>barplot(table.caff.marital,
         col = c(&quot;red&quot;,&quot;green&quot;,&quot;blue&quot;),
         legend.text = c(&quot;casados&quot;, &quot;divorciados&quot;, &quot;solteros&quot;))</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-219-1.png" width="672" /></p>
<p>Si deseas graficar las dos dimensiones de una tabla pero no deseas que estén agrupadas dentre de una sóla barra, puedes utilizar el argumento <code>beside = T</code> para este fin.</p>
<p>Mira las distintas opciones que puedes utilizar para crear tu gráfica de barras.</p>
<pre class="r"><code>par(mfrow = c(2,2))
barplot(caff.marital, col=&quot;white&quot;)
barplot(t(caff.marital), col = &quot;white&quot;)
barplot(t(caff.marital), col = &quot;white&quot;, beside = T)
barplot(prop.table(t(caff.marital),2), col=&quot;white&quot;, beside = T)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-220-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow = c(1,1))</code></pre>
</div>
<div id="gráfica-de-barras" class="section level4">
<h4>Gráfica de barras</h4>
<p>Una idea para que tu gráfica se vea mejor</p>
<pre class="r"><code>barplot(prop.table(t(table.caff.marital),2),beside = T,
         legend.text = colnames(table.caff.marital),
         col = c(&quot;white&quot;, &quot;grey80&quot;, &quot;grey50&quot;, &quot;black&quot;))</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-221-1.png" width="672" /></p>
<p><code>R</code> no tiene una forma de encontrar la mejor posición para la leyenda y en ocasiones esta se sobrepondrá sobre tu gráfica.</p>
<p>Para tener un mayor control puedes usar la función <code>legend</code>.</p>
<p>Con el ratón puedes hacer cick en la gráfica generada y obtener coordenadas para la leyenda usando la función <code>locator</code>.</p>
<p>Estas funciones están fuera del alcance del curso, sin embargo, se motiva a los usuarios avanzados que las investiguen para su uso.</p>
</div>
<div id="diagrama-de-puntos-de-cleveland" class="section level4">
<h4>Diagrama de puntos de Cleveland</h4>
<p>El diagrama de puntos de Cleveland es nombrado a partir de William S. Cleveland (1994) está formulado con la misma información de una gráfica de barras pero ofrece una impresión visual muy diferente. Para ejecutarlo usar</p>
<pre class="r"><code>dotchart(t(table.caff.marital), lcolor = &quot;black&quot;)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-222-1.png" width="672" /></p>
</div>
<div id="diagramas-de-pastel" class="section level4">
<h4>Diagramas de pastel</h4>
<p>Veamos como se ven los datos de consumo de cafeína contra el estatus marital</p>
<pre class="r"><code>slices &lt;- c(&quot;white&quot;, &quot;grey80&quot;, &quot;grey50&quot;, &quot;black&quot;)
pie(table.caff.marital[&quot;Casados&quot;,], main=&quot;Casados&quot;, col=slices)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-223-1.png" width="672" /></p>
<pre class="r"><code>pie(table.caff.marital[&quot;Divorciados&quot;,], main=&quot;Divorciados&quot;, col=slices)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-223-2.png" width="672" /></p>
<pre class="r"><code>pie(table.caff.marital[&quot;Solteros&quot;,], main=&quot;Solteros&quot;, col=slices)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-223-3.png" width="672" /></p>
<pre class="r"><code>par(opar)</code></pre>
</div>
</div>
<div id="ejercicios-2" class="section level3">
<h3>Ejercicios</h3>
<ul>
<li><p>Explore distintas formas de gráficas de lineas y puntos. Cambie el tipo de línea, el grosor de la línea y el color.</p></li>
<li><p>Al graficar <code>plot(rnorm(10), type = "o")</code> las líneas son visibles dentro de los símbolos dibujados. ¿Cómo puedes evitar esto?</p></li>
<li><p>Crea un histograma de los datos <code>react</code>. Debido al alto grado de discretización de los datos, el histograma estará sesgado. ¿Por qué? Puedes utilizar la función <code>truehist()</code> del paquete <code>MASS</code> como reemplazo.</p></li>
</ul>
</div>
<div id="soluciones" class="section level3">
<h3>Soluciones</h3>
<ul>
<li>Este es un ejemplo.</li>
</ul>
<pre class="r"><code>plot(rnorm(10), type = &quot;b&quot;, col=&quot;blue&quot;, pch=1, lwd=2)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-224-1.png" width="672" /></p>
<ul>
<li>Podemos cambiar el símbolo dibujado por uno sólido.</li>
</ul>
<pre class="r"><code>plot(rnorm(10), type = &quot;o&quot;, col=&quot;black&quot;, pch=19)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-225-1.png" width="672" /></p>
<ul>
<li></li>
</ul>
<pre class="r"><code>hist(react)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-226-1.png" width="672" /></p>
<pre class="r"><code>library(MASS)</code></pre>
<pre><code>## 
## Attaching package: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;juul&#39;:
## 
##     menarche</code></pre>
<pre class="r"><code>truehist(react)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-226-2.png" width="672" /></p>
</div>
</div>
<div id="otros-tópicos" class="section level2">
<h2>Otros Tópicos</h2>
<div id="descripción-del-módulo-6" class="section level3">
<h3>Descripción del módulo</h3>
<div id="objetivos-6" class="section level4">
<h4>Objetivos</h4>
<p>A continuación se presentan algunos tópicos que pueden ser de interés para usuarios avanzados en <code>R</code>. El detalle del conocimiento de estos tópicos va más allá de la funcionalidad base de <code>R</code> o requiere de estudios previos en estadística.</p>
<p>Los tópicos mostrados a continuación son:</p>
<ul>
<li><code>data.table</code></li>
<li><code>dplyr</code></li>
<li>Pronósticos</li>
</ul>
<p>La presentación de cada tópico es introductoria, y su fin es el de ofrecer una guía a usuario avanzados que deseen profundizar en el uso de <code>R</code>.</p>
</div>
</div>
<div id="data-tables" class="section level3">
<h3>Data Tables</h3>
<p>Cuando se manipulan datos es común querer obtener subconjuntos, agrupar, actualizar, o incluso unir distintos conjuntos en un solo.</p>
<p><code>data.tables</code> ofrece una estructura que permite mantener estos comandos de forma concisa y consistente.</p>
<p>Reduces la necesidad de utilizar funciones externas que te ayuden a hacer el análisis.*</p>
<p>Reducir los tiempos de procesamiento al utilizar comandos optimizados.</p>
<div id="lee-archivos-de-datos" class="section level4">
<h4>Lee archivos de datos</h4>
<p>Puedes usar la función fast file reader <code>fread</code> de <code>data.table</code></p>
<pre class="r"><code>secretinBD &lt;- fread(&quot;secretinBD.txt&quot;)</code></pre>
<p>El archivo <code>secretinBD.txt</code> se encuentra entre tus archivos de la clase. Descárgalo y léelo usando la función anterior.</p>
<p>La función <code>fread</code> acepta <code>http</code> y <code>https</code> de forma directa.</p>
</div>
<div id="lee-archivos-de-datos-1" class="section level4">
<h4>Lee archivos de datos</h4>
<p>Para saber cuantos reglones y columnas tiene tu archivo usa</p>
<pre class="r"><code>dim(secretinBD)</code></pre>
</div>
<div id="crea-un-data-table" class="section level4">
<h4>Crea un data table</h4>
<p>Puedes crear tu propio data table usando la función <code>data.table</code></p>
<pre class="r"><code>library(data.table)</code></pre>
<pre><code>## Warning: package &#39;data.table&#39; was built under R version 4.0.2</code></pre>
<pre class="r"><code>DT = data.table(ID = c(&quot;b&quot;,&quot;b&quot;,&quot;b&quot;,&quot;a&quot;,&quot;a&quot;,&quot;c&quot;),
                 a = 1:6,
                 b = 7:12,
                 c = 13:18)
DT</code></pre>
<pre><code>##    ID a  b  c
## 1:  b 1  7 13
## 2:  b 2  8 14
## 3:  b 3  9 15
## 4:  a 4 10 16
## 5:  a 5 11 17
## 6:  c 6 12 18</code></pre>
<p>También puedes utilizar el comando <code>as.data.table</code> para convertir un objeto existente.</p>
</div>
<div id="características" class="section level4">
<h4>Características</h4>
<p>A diferencia de <code>data.frames</code>, <code>data.table</code> nunca convierte una columna de caracteres en factores por defecto.</p>
<p>Los número de las filas se imprimen con <code>:</code> para mejorar la visualización.</p>
<p>Cuando la cantidad de filas a imprimir excede el parámetro global (por defectos es 100) sólo se imprimen los primeros cinco y los últimos cinco reglones.</p>
<p>El parámetro global se accede por medio de <code>datatable.print.nrows</code>:</p>
<pre class="r"><code>getOption(&quot;datatable.print.nrows&quot;)</code></pre>
<pre><code>## [1] 100</code></pre>
</div>
<div id="nuevas-características" class="section level4">
<h4>Nuevas características</h4>
<p>A diferencia de un <code>data.frame</code>, por medio de <code>data.table</code> puedes filtrar, seleccionar y agrupar de forma nativa y eficiente.</p>
<p>Para este fin se sigue la sintaxis <code>DT[i,j,by]</code>, que en voz alta se lee algo así: <em>Toma DT, filtra las filas usando <code>i</code>, luego selecciona <code>j</code>, agrupando por by</em>.</p>
</div>
<div id="filtrando-filas" class="section level4">
<h4>Filtrando filas</h4>
<p>Siguendo la sintaxis de <code>data.table</code>.</p>
<pre class="r"><code>secretinBD[gluc &gt; 85 &amp; person == &quot;A&quot;]</code></pre>
</div>
<div id="ordenamientos-1" class="section level4">
<h4>Ordenamientos</h4>
<p>Podemos ordenar los datos más rápidamente que en un data frame usando la función <code>order</code>. A continuación ordenamos los datos de secretinBD por <code>person</code> en forma ascendente y por <code>gluc</code> en forma descendente y presentamos los primeros resultados.</p>
<pre class="r"><code>head(secretinBD[order(person, -gluc)])</code></pre>
</div>
<div id="seleccionando-columnas" class="section level4">
<h4>Seleccionando columnas</h4>
<p>Sólo tienes que indicar el nombre sin comillas.</p>
<pre class="r"><code>head(secretinBD[,gluc]) #salida es un arreglo</code></pre>
<pre class="r"><code>head(secretinBD[,list(gluc)]) #salida es un data table</code></pre>
</div>
<div id="aplica-una-función-a-las-filas-según-clasificación" class="section level4">
<h4>Aplica una función a las filas según clasificación</h4>
<p>A continuación se muestra como obtener el promedio de <code>gluc</code> según la persona.</p>
<pre class="r"><code>secretinBD[,list(Promedio = mean(gluc)), list(person)]</code></pre>
</div>
<div id="contar-filas-según-clasificación" class="section level4">
<h4>Contar filas según clasificación</h4>
<p>A continuación se muestra como obtener el total de filas según la persona.</p>
<pre class="r"><code>secretinBD[,list(.N), list(person)]</code></pre>
<p><code>R</code> reconoce el símbolo especial <code>.N</code> que indica el número de observaciones en el grupo actual.</p>
</div>
<div id="para-más-información" class="section level4">
<h4>Para más información</h4>
<p>Para más información visita el documento <em>Introduction to data.table</em> en el CRAN de R.</p>
<p>Encontrarás <code>data.table</code> especialmente útil en su manejo de grandes volúmenes de datos.</p>
</div>
<div id="introducción-a-dplyr" class="section level4">
<h4>Introducción a <code>dplyr</code></h4>
<p>El paquete <code>dplyr</code> provee de una sintaxis simplificada para tareas comunes que de entre lo que ya puedes hacer con un <code>data.frame</code>.</p>
<p>El paquete no ofrece ninguna funcionalidad nueva, simplemente una sintaxis conveniente.</p>
<p>El conveniente para ser usado en bases de datos pequeñas o medianas.</p>
</div>
<div id="ejemplo-5" class="section level4">
<h4>Ejemplo</h4>
<p>Aquí están algunos ejemplos de la sintaxis de <code>dplyr</code>:</p>
<ul>
<li><code>filter()</code> para seleccionar casos según sus valores.</li>
<li><code>arrange()</code> para reordenar los reglones.</li>
<li><code>select()</code> y rename() seleccionar las variables según su nombre.</li>
<li><code>mutate()</code> y <code>transmute()</code> para agregar nuevas variables que son función de las existentes.</li>
<li><code>summarise()</code> para condensar múltiples valores en uno solo.</li>
<li><code>sample_n()</code> y <code>sample_frac()</code> sirven para tomar muestras aleatorias.</li>
</ul>
</div>
<div id="para-más-información-1" class="section level4">
<h4>Para más información</h4>
<p>Para más información sobre el paquete <code>dplyr</code> te recomandamos leer el manual <em>Introduction to dplyr</em> en el CRAN de R.</p>
</div>
</div>
<div id="regresión-y-correlación" class="section level3">
<h3>Regresión y correlación</h3>
<div id="introducción-a-regresión-y-correlación" class="section level4">
<h4>Introducción a regresión y correlación</h4>
<p>Cuando se analizan datos que vienen pareja, surgen inquietudes sobre la relación que pueda existir entre los mismos y sí es posible utilizar una parte de ellos para predecir la restante.</p>
<p>En estadística, el análisis de regresión y correlación trata de responder estas dudas al ajustar modelos lineales a los datos que posteriormente pueden ser utilizados para hacer pronósticos.</p>
<p>A modo de ejemplo veremos una de estas metodologías.</p>
</div>
<div id="visualización-de-los-datos" class="section level4">
<h4>Visualización de los datos</h4>
<p>A continuación haremos un ejemplo utilizando el <code>data.frame</code> con nombre <code>mtcars</code></p>
<p>Puedes acceder a la documentación de <code>mtcars</code> ingresando a</p>
<pre class="r"><code>?mtcars       #para ver descripci?n de los datos. 
View(mtcars)  #para ver los datos.</code></pre>
<p>La función <code>View</code> despliega los datos en forma de hoja de cálculo, lo que facilita su visualización.</p>
</div>
<div id="analizamos-la-relación-de-los-datos" class="section level4">
<h4>Analizamos la relación de los datos</h4>
<p>Estudiaremos la relación entre la fuerza medidas en caballos (hp) y el consumo de combustible en millas por galón (mpg). Hacemos un diagrama de dispersión.</p>
<pre class="r"><code>plot(mtcars$hp, mtcars$mpg, xlab = &quot;HP&quot;, ylab = &quot;MPG&quot;)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-238-1.png" width="672" /></p>
</div>
<div id="correlación" class="section level4">
<h4>Correlación</h4>
<p>La función <code>cor</code> nos ayuda a medir la correlación lineal que puede existir entre dos variables.</p>
<pre class="r"><code>?cor</code></pre>
<pre><code>## starting httpd help server ... done</code></pre>
<pre class="r"><code>cor(x = mtcars$hp, y = mtcars$mpg, method = &quot;pearson&quot;)</code></pre>
<pre><code>## [1] -0.7761684</code></pre>
<p>El argumento <code>method = "pearson"</code> indica que estamos utilizando el coeficiente de correlación de Pearson, por mucho el más usado en la práctica.</p>
<p>Algunas reglas a considerar:</p>
<ul>
<li>Un valor cercano a 1 indica una correlación positiva fuerte.</li>
<li>Un valor cercano a -1 indica una correlación negativa fuerte.</li>
<li>Valores cercanos a 0 indican baja correlación.</li>
</ul>
<blockquote>
<p>Cuidado El coeficiente de correlación de Pearson sólo mide la relación lineal entre variables. Un valor cercano a cero del coeficiente de correlación no necesariamente indica baja correlación, pues la correlación de los datos puede ser no lineal. Para evitar malas conclusiones, siempre grafica tus datos.</p>
</blockquote>
<p>La función <code>cor</code> puede analizar todas las variables que desees en un data frame al mismo tiempo</p>
<pre class="r"><code>cor(mtcars[,c(1,2,3,4)], method = &quot;pearson&quot;)</code></pre>
<pre><code>##             mpg        cyl       disp         hp
## mpg   1.0000000 -0.8521620 -0.8475514 -0.7761684
## cyl  -0.8521620  1.0000000  0.9020329  0.8324475
## disp -0.8475514  0.9020329  1.0000000  0.7909486
## hp   -0.7761684  0.8324475  0.7909486  1.0000000</code></pre>
<p>Esta es una matriz de correlaciones.</p>
</div>
<div id="regresión" class="section level4">
<h4>Regresión</h4>
<p>La función <code>lm</code> nos permite hacer un análisis de regresión y ajustar modelos lineales que no ayuden a predecir una variable de interés.</p>
<pre class="r"><code>?lm
lm.mpg&lt;-lm(mpg~hp, data = mtcars)
lm.mpg</code></pre>
<pre><code>## 
## Call:
## lm(formula = mpg ~ hp, data = mtcars)
## 
## Coefficients:
## (Intercept)           hp  
##    30.09886     -0.06823</code></pre>
<p>La recta que ajustamos es <span class="math inline">\(mpg = 30.09886 - 0.06823 hp\)</span>.</p>
<p>Podemos usar esta recta para hacer predicciones. Pero primero, hay que verificar que el ajuste sea bueno.</p>
</div>
<div id="verificamos-el-ajuste-de-la-regresión" class="section level4">
<h4>Verificamos el ajuste de la regresión</h4>
<p>Cuando trabajamos con una regresión lineal simple. Una forma intuitiva (existen otras más avanzadas) de evaluar el ajuste de la línea es graficándola junto a los datos.</p>
<pre class="r"><code>x = mtcars$hp
y = mtcars$mpg
yhat = fitted(lm.mpg)
plot(x = x,y = y, pch = 19, xlab = &quot;HP&quot;, ylab = &quot;MPG&quot;)
points(sort(x), yhat[order(x)], type=&quot;l&quot;, col=&quot;red&quot;, lwd=2)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-242-1.png" width="672" /></p>
<p>Nota que el ajuste parece no ser muy bueno.</p>
</div>
<div id="mejoramos-el-ajuste" class="section level4">
<h4>Mejoramos el ajuste</h4>
<p>Transformamos la variable independiente <code>x</code> para mejorar el ajuste.</p>
<pre class="r"><code>y = mtcars$mpg
x = mtcars$hp
trans.x &lt;- log(x)
lm.mpg&lt;-lm(y~trans.x)
plot(x,y, pch = 19, xlab = &quot;HP&quot;, ylab = &quot;MPG&quot;)
yhat = fitted(lm.mpg)
points(sort(x), yhat[order(x)], type=&quot;l&quot;, col=&quot;red&quot;, lwd=2)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-243-1.png" width="672" /></p>
<p>El ajuste se observa mucho mejor. Ahora podemos utilizar la ecuación para hacer predicciones con más confianza.</p>
</div>
</div>
</div>
<div id="pruebas-de-hipótesis" class="section level2">
<h2>Pruebas de Hipótesis</h2>
<div id="objetivos-7" class="section level3">
<h3>Objetivos</h3>
<p>A continuación se presentan algunas pruebas estadísticas usadas para analizar datos en <code>R</code>. El detalle del conocimiento de estos tópicos va más allá de la funcionalidad base de <code>R</code> o requiere de estudios previos en estadística.</p>
<p>Las pruebas a considerar se muestran a continuación:</p>
<ul>
<li>Prueba de Normalidad</li>
<li>Prueba de Medias</li>
<li>Prueba de varianza</li>
<li>Prueba de proporciones</li>
</ul>
</div>
<div id="prueba-de-normalidad" class="section level3">
<h3>Prueba de Normalidad</h3>
<div id="gráfico-cuantil-cuantil" class="section level4">
<h4>Gráfico Cuantil-Cuantil</h4>
<p>Un gráfico Cuantil-Cuantil permite observar cuan cerca está la distribución de un conjunto de datos a alguna distribución ideal ó comparar la distribución de dos conjuntos de datos.</p>
<p><em>Ejemplo</em>: comparación con distribución normal</p>
<pre class="r"><code>#generar 100 datos normales
x &lt;- rnorm(100)</code></pre>
<pre class="r"><code>#graficar sus cuantiles
qqnorm(x)
#graficar la recta con mejor ajuste
qqline(x)</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-245-1.png" width="672" /></p>
<p>Comparar la distribución de dos conjuntos de datos</p>
<pre class="r"><code>#primer conjunto de datos
x &lt;- rnorm(100)
#segundo conjunto de datos
y &lt;- rnorm(100)
qqplot(x,y)
qqline(x,y)</code></pre>
<pre><code>## Warning in if (datax) {: la condición tiene longitud &gt; 1 y sólo el primer
## elemento será usado</code></pre>
<p><img src="about_files/figure-html/unnamed-chunk-246-1.png" width="672" /></p>
</div>
<div id="prueba-de-shaphiro-wilks" class="section level4">
<h4>Prueba de Shaphiro-Wilks</h4>
<p>Se utiliza para contrastar la normalidad de un conjunto de datos. Es una de las más utilizadas y eficientes para comprobar la normalidad de una variable.</p>
<p><em>Interpretación</em>: Siendo la hipótesis nula que la población está distribuida normalmente, si el p-valor es menor a alfa (nivel de significancia) entonces la hipótesis nula es rechazada (se concluye que los datos no vienen de una distribución normal). Si el p-valor es mayor a alfa, se concluye que no se puede rechazar dicha hipótesis.</p>
<p>Ejemplo</p>
<pre class="r"><code># Creamos una variable normal con 100 valores
x &lt;- rnorm(100) 
x.test &lt;- shapiro.test(x)
print(x.test)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  x
## W = 0.99299, p-value = 0.8876</code></pre>
<p>Como el valor de <span class="math inline">\(p &gt; 0.05\)</span>, entonces podemos inferir que la distribución de los datos es una distribución normal.</p>
</div>
</div>
<div id="prueba-de-medias" class="section level3">
<h3>Prueba de Medias</h3>
<div id="prueba-t-de-student" class="section level4">
<h4>Prueba t de Student</h4>
<p>Se utiliza para comprobar la igualdad de las medias de dos muestras o una muestra. También para comprobar si la media de una muestra es igual a una media teórica determinada. Los datos tienen que tener distribución normal (véase la prueba de Shapiro-Wilk).</p>
<p><em>Interpretación</em>: Siendo la hipótesis nula que las medias de las muestras son iguales, si el <span class="math inline">\(p\)</span>-valor es menor a alfa (nivel de significancia) entonces la hipótesis nula es rechazada (se concluye que los datos tienen diferentes medias). Si el <span class="math inline">\(p\)</span>-valor es mayor a alfa, se concluye que no se puede rechazar dicha hipótesis.</p>
<p><em>Ejemplo</em>: Comparación de dos muestras</p>
<pre class="r"><code>x1 &lt;- rnorm(100,10) # Variable aleatoria de media 10
x2 &lt;- rnorm(100,10.5) # Variable aleatoria de media 10.5
test &lt;- t.test(x1,x2) # Prueba t de Student
print(test)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  x1 and x2
## t = -4.4563, df = 195.42, p-value = 1.403e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.8331228 -0.3219424
## sample estimates:
## mean of x mean of y 
##  9.993251 10.570784</code></pre>
<p>Como el <span class="math inline">\(p\)</span>-value es <span class="math inline">\(&lt;0.05\)</span> podemos afirmar que las muestras difieren en su media, es decir, los dos variables son diferentes.</p>
</div>
<div id="anova" class="section level4">
<h4>ANOVA</h4>
<p>Se usa para comparar las medias de dos o más grupos. Esta técnica puede generalizarse también para estudiar los posibles efectos de los factores sobre la varianza de una variable.</p>
<p>La hipótesis nula de la que parten los diferentes tipos de ANOVA es que la media de la variable estudiada es la misma en los diferentes grupos, en contraposición a la hipótesis alternativa de que al menos dos medias difieren de forma significativa. ANOVA permite comparar múltiples medias, pero lo hace mediante el estudio de las varianzas.</p>
<p>Ejemplo en formato <code>.csv</code> para realizar un análisis:</p>
<pre class="r"><code>Subtype,Gender,Expression
A,m,-0.54
A,m,-0.8
A,m,-1.03
A,m,-0.41
B,f,-0.67
B,m,-0.77
B,f,-0.03
B,m,-0.12
C,m,1.67
C,m,0.81
C,f,-1.81
C,f,-1.18</code></pre>
<p>Análisis ANOVA de una cola:</p>
<pre class="r"><code>a = aov(Expression~Subtype, data=x)
summary(a)</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## Subtype      2  0.645  0.3223   0.333  0.725
## Residuals    9  8.702  0.9669</code></pre>
<p>Poner atencion en la formula, la variable dependiente <code>Expression</code> se encuentra antes de la variable independiente <code>Subtype</code>.</p>
<p>Análisis ANOVA de dos colas:</p>
<pre class="r"><code>a = aov(Expression~Subtype*Gender, data=x)
summary(a)</code></pre>
<pre><code>##                Df Sum Sq Mean Sq F value  Pr(&gt;F)   
## Subtype         2  0.645   0.322    1.86 0.22495   
## Gender          1  3.485   3.485   20.11 0.00285 **
## Subtype:Gender  1  4.004   4.004   23.11 0.00195 **
## Residuals       7  1.213   0.173                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Aquí, la variable dependiente es <code>Expression</code>. Las variables <code>Subtype</code> and <code>Age</code> son independientes.</p>
</div>
</div>
<div id="prueba-de-varianza" class="section level3">
<h3>Prueba de Varianza</h3>
<div id="prueba-f" class="section level4">
<h4>Prueba F</h4>
<p>Se usa para comprobar la igualdad de varianzas entre dos grupos de datos. Nos puede ser útil en multitud de situaciones, por ejemplo, cuando tenemos dos máquinas que fabrian lo mismo (por ejemplo, rodamientos), y queremos saber si lo hacen con la misma variabilidad. Para poner un ejemplo, generemos datos de dos distribuciones normales con distinta varianza y veamos si el test detecta esta situación:</p>
<pre class="r"><code>x &lt;- rnorm(50, mean = 0, sd = 2)
y &lt;- rnorm(30, mean = 1, sd = 1)
var.test(x, y)</code></pre>
<pre><code>## 
##  F test to compare two variances
## 
## data:  x and y
## F = 3.8728, num df = 49, denom df = 29, p-value = 0.0002132
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  1.945802 7.286415
## sample estimates:
## ratio of variances 
##           3.872835</code></pre>
<p>Como vemos, el <span class="math inline">\(p\)</span>-valor sale prácticamente cero: rechazaremos la hipótesis de que los conjuntos de datos <code>x</code> e <code>y</code> provienen de distribuciones con la misma varianza.</p>
</div>
<div id="homogéneidad-de-varianzas" class="section level4">
<h4>Homogéneidad de Varianzas</h4>
<p>Permite contrastar la igualdad de varianza en 2 o más poblaciones sin necesidad de que el tamaño de los grupos sea el mismo. Es sensible a la falta de normalidad, pero si se está seguro de que los datos provienen de una distribución normal, es la mejor opción.</p>
<p><em>Ejemplo:</em></p>
<pre class="r"><code>data(&quot;iris&quot;)
a &lt;- iris[iris$Species == &quot;versicolor&quot;, &quot;Petal.Length&quot;]
b &lt;- iris[iris$Species == &quot;virginica&quot;, &quot;Petal.Length&quot;]
bartlett.test(list(a,b))</code></pre>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  list(a, b)
## Bartlett&#39;s K-squared = 1.249, df = 1, p-value = 0.2637</code></pre>
<p>Como el valor de <span class="math inline">\(p\)</span> es mayor a 0.05, el test no encuentra diferencias significativas entre las varianzas de los dos grupos.</p>
</div>
</div>
<div id="prueba-de-proporciones" class="section level3">
<h3>Prueba de Proporciones</h3>
<div id="igualdad-de-proporciones" class="section level4">
<h4>Igualdad de Proporciones</h4>
<p>Se usa para determinar si las proporciones en varios grupos son las mismas, o bien que dichas proporciones equivalen a unas determinadas.</p>
<p><em>Ejemplo:</em> Para empezar, tiraremos una moneda al aire 100 veces, y nos preguntaremos si la proporción de caras puede ser considerada el 50%:</p>
<pre class="r"><code>caras &lt;- rbinom(1, size=100, pr = .5)
caras</code></pre>
<pre><code>## [1] 60</code></pre>
<pre class="r"><code>prop.test(caras,100)</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  caras out of 100, null probability 0.5
## X-squared = 3.61, df = 1, p-value = 0.05743
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.4970036 0.6952199
## sample estimates:
##   p 
## 0.6</code></pre>
<p>Como el <span class="math inline">\(p\)</span>-valor es muy alto, 0.92, no rechazaremos la hipótesis nula de que <span class="math inline">\(p=0.5\)</span>.</p>
<p>Supongamos ahora que queremos saber si dos muestras han salido de la misma población.</p>
<p><em>Ejemplo:</em> se quiere saber si las mujeres estudian un grupo de carreras diferentes en la misma proporcion. Para ello miramos la lista de matriculados en cuatro carreras y comprobamos si las proporciones de mujeres en las mismas coinciden:</p>
<pre class="r"><code>estudiantes&lt;-c(100,200,50,500)
names(estudiantes)&lt;-c(&quot;quimica&quot;,&quot;derecho&quot;,
                      &quot;matematicas&quot;,&quot;economia&quot;)
estudiantes</code></pre>
<pre><code>##     quimica     derecho matematicas    economia 
##         100         200          50         500</code></pre>
<pre class="r"><code>estudiantes.mujeres&lt;-c(60,120,10,200)
prop.test(estudiantes.mujeres,estudiantes)</code></pre>
<pre><code>## 
##  4-sample test for equality of proportions without continuity
##  correction
## 
## data:  estudiantes.mujeres out of estudiantes
## X-squared = 44.537, df = 3, p-value = 1.16e-09
## alternative hypothesis: two.sided
## sample estimates:
## prop 1 prop 2 prop 3 prop 4 
##    0.6    0.6    0.2    0.4</code></pre>
<p>La conclusión es que no. Las mujeres, en este ejemplo, se matriculan de las carreras en distinta proporcion.</p>
</div>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
